#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 150000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 160000

#import "Xcode_13_0_XCTestCore_CDStructures.h"
#import "Xcode_13_0_SharedHeader.h"
#import "Xcode_13_0_XCTTestIdentifierSet.h"

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

__attribute__((visibility("hidden")))
@interface _XCTTestIdentifierSet_Set : XCTTestIdentifierSet
{
    NSSet *_testIdentifiers;
}

- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (_Bool)containsTestIdentifier:(id)arg1;
- (id)anyTestIdentifier;
- (unsigned long long)count;
- (id)initWithTestIdentifiers:(const /* was `id *` before dump.py */ void * )arg1 count:(unsigned long long)arg2;

@end

#endif