#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 150000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 160000

#import "Xcode_13_0_XCTestCore_CDStructures.h"
#import "Xcode_13_0_SharedHeader.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTRerunPolicy : NSObject <NSSecureCoding>
{
    long long _rerunMode;
    long long _maximumIterations;
}

+ (_Bool)supportsSecureCoding;
+ (long long)rerunModeFromString:(id)arg1;
+ (id)stringFromRerunMode:(long long)arg1;
+ (id)defaultRerunPolicy;
@property(readonly) long long maximumIterations; // @synthesize maximumIterations=_maximumIterations;
@property(readonly) long long rerunMode; // @synthesize rerunMode=_rerunMode;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isDefault;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)repetitionPolicyRepresentation;
- (id)initWithDictionary:(id)arg1;
- (id)initWithFixedIterations:(long long)arg1;
- (id)initWithMaximumIterationsUntilSuccess:(long long)arg1;
- (id)initWithMaximumIterationsUntilFailure:(long long)arg1;
- (id)initWithRerunMode:(long long)arg1 maximumIterations:(long long)arg2;

@end

#endif