#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 150000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 160000

#import "Xcode_13_0_XCTestCore_CDStructures.h"
#import "Xcode_13_0_SharedHeader.h"
#import "Xcode_13_0_XCTIssueHandling.h"
#import <Foundation/Foundation.h>
#import <XCTest/XCTest.h>

@class XCTExpectedFailureContextManager, XCTTestIdentifier, XCTestObservationCenter, XCTestRun;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTest ()
{
    XCTExpectedFailureContextManager *_expectedFailureContextManager;
    XCTestRun *_testRun;
    XCTestObservationCenter *_observationCenter;
}

+ (id)bundle;
@property(readonly, getter=_activityAggregateStatistics) NSDictionary *activityAggregateStatistics;
@property(readonly) NSBundle *bundle;
- (void)expectFailureWithContext:(id)arg1 inBlock:(CDUnknownBlockType)arg2;
- (void)expectFailureWithContext:(id)arg1;
- (void)_checkForExpectedFailureMatchingIssue:(id)arg1;
- (id)expectedFailureContextManager;
- (void)handleIssue:(id)arg1;
- (long long)defaultExecutionOrderCompare:(id)arg1;
@property(readonly) NSString *nameForLegacyLogging;
@property(readonly) NSString *languageAgnosticTestMethodName;
@property(readonly) NSString *languageAgnosticTestClassName;
- (void)tearDown;
- (void)setUp;
- (_Bool)_shouldRepeatTest;
- (void)runTest;
@property(retain) XCTestObservationCenter *observationCenter; // @synthesize observationCenter=_observationCenter;
@property(readonly) Class _requiredTestRunBaseClass;
- (id)_duplicate;
- (void)removeTestsWithIdentifierInSet:(id)arg1;
@property(readonly) NSString *_methodNameForReporting;
@property(readonly) NSString *_classNameForReporting;

// Remaining properties
@property(readonly, getter=_identifier) XCTTestIdentifier *identifier; // @dynamic identifier;

@end

#endif