#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 150000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 160000

#import "Xcode_13_0_XCTestCore_CDStructures.h"
#import "Xcode_13_0_SharedHeader.h"
#import "Xcode_13_0_XCTMessagingRole_BundleRequesting.h"
#import "Xcode_13_0_XCTMessagingRole_CapabilityExchange.h"
#import "Xcode_13_0_XCTMessagingRole_EventSynthesis.h"
#import "Xcode_13_0_XCTMessagingRole_ForcePressureSupportQuerying.h"
#import "Xcode_13_0_XCTMessagingRole_HIDEventRecording.h"
#import "Xcode_13_0_XCTMessagingRole_MemoryTesting.h"
#import "Xcode_13_0_XCTMessagingRole_ProtectedResourceAuthorization.h"
#import "Xcode_13_0_XCTMessagingRole_SignpostRequesting.h"
#import "Xcode_13_0_XCTMessagingRole_SiriAutomation.h"
#import "Xcode_13_0_XCTMessagingRole_SystemConfiguration.h"
#import "Xcode_13_0__XCTMessaging_VoidProtocol.h"

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTMessagingChannel_RunnerToDaemon <XCTMessagingRole_ProtectedResourceAuthorization, XCTMessagingRole_CapabilityExchange, XCTMessagingRole_EventSynthesis, XCTMessagingRole_SiriAutomation, XCTMessagingRole_MemoryTesting, XCTMessagingRole_BundleRequesting, XCTMessagingRole_ForcePressureSupportQuerying, XCTMessagingRole_SignpostRequesting, XCTMessagingRole_HIDEventRecording, XCTMessagingRole_SystemConfiguration, _XCTMessaging_VoidProtocol>

@optional
- (void)__dummy_method_to_work_around_68987191;
@end

#endif
