#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 150000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 160000

#import "Xcode_13_0_XCTestCore_CDStructures.h"
#import "Xcode_13_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@protocol XCTMessagingRole_TestReporting, XCTReportingSessionConfiguration;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTReportingSession : NSObject
{
    id <XCTReportingSessionConfiguration> _configuration;
    id <XCTMessagingRole_TestReporting> _IDEProxy;
}

+ (void)beginReportingSessionWithIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly) id <XCTReportingSessionConfiguration> configuration; // @synthesize configuration=_configuration;
- (void)finishWithCompletion:(CDUnknownBlockType)arg1;
- (id)reportSuiteStartedWithName:(id)arg1 atDate:(id)arg2;
- (void)reportStarted;
- (id)initWithIDEProxy:(id)arg1 configuration:(id)arg2;

@end

#endif