#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 150000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 160000

#import "Xcode_13_0_XCTestCore_CDStructures.h"
#import "Xcode_13_0_SharedHeader.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTMetricHelper : NSObject
{
}

+ (id)determineDeltaFor:(id)arg1 withMetricProcessID:(id)arg2;
+ (id)createFilterWithPid:(int)arg1 andTag:(id)arg2;
+ (void)formatIdentifierPrefix:(id *)arg1 andDisplayName:(id *)arg2 withProcessIdentifierName:(id)arg3 andProcessDisplayName:(id)arg4 givenProcessID:(id)arg5;
+ (void)addMetricToMeasurements:(id)arg1 sampleTag:(id)arg2 identifier:(id)arg3 displayName:(id)arg4 measurements:(id)arg5 skipConversion:(_Bool)arg6 polarity:(long long)arg7;

@end

#endif