#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 150000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 160000

#import "Xcode_13_0_XCTestCore_CDStructures.h"
#import "Xcode_13_0_SharedHeader.h"

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct _CSTypeRef {
    unsigned long long _opaque_1;
    unsigned long long _opaque_2;
};

#pragma mark Typedef'd Structures

typedef struct {
    CDUnknownFunctionPointerType release;
    CDUnknownFunctionPointerType retain;
    CDUnknownFunctionPointerType isNull;
    CDUnknownFunctionPointerType getArchitectureForName;
    CDUnknownFunctionPointerType symbolicatorCreateWithTask;
    CDUnknownFunctionPointerType symbolicatorForeachSymbolicatorWithPath;
    CDUnknownFunctionPointerType symbolicatorForeachSharedCache;
    CDUnknownFunctionPointerType symbolOwnerGetBaseAddress;
    CDUnknownFunctionPointerType symbolicatorGetArchitecture;
    CDUnknownFunctionPointerType symbolicatorForeachSymbolOwnerWithPathAtTime;
    CDUnknownFunctionPointerType symbolicatorGetSymbolOwnerWithUUIDAtTime;
    CDUnknownFunctionPointerType symbolicatorGetSymbolOwnerWithAddressAtTime;
    CDUnknownFunctionPointerType symbolOwnerGetName;
    CDUnknownFunctionPointerType symbolOwnerGetSymbolWithAddress;
    CDUnknownFunctionPointerType symbolOwnerGetSourceInfoWithAddress;
    CDUnknownFunctionPointerType symbolGetName;
    CDUnknownFunctionPointerType sourceInfoGetPath;
    CDUnknownFunctionPointerType sourceInfoGetLineNumber;
} CDStruct_37ea9563;

typedef struct {
    long long _field1;
    long long _field2;
    long long _field3;
} CDStruct_2ec95fd7;

#endif