#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 150000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 160000

#import "Xcode_13_0_XCTestCore_CDStructures.h"
#import "Xcode_13_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@protocol XCTSignpostListener;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTRemoteSignpostListenerProxy <NSObject>
@property __weak id <XCTSignpostListener> signpostListener;
@property(readonly) _Bool supportsSignpostListening;
- (void)unregisterForSignpostsWithToken:(NSUUID *)arg1;
- (void)registerForSignpostsFromSubsystem:(NSString *)arg1 category:(NSString *)arg2 intervalTimeout:(double)arg3 reply:(void (^)(NSUUID *, NSError *))arg4;
@end

#endif
