#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 150000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 160000

#import "Xcode_13_0_XCTestCore_CDStructures.h"
#import "Xcode_13_0_SharedHeader.h"

@class XCTCapabilities;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTMessagingRole_ControlSessionInitiation
- (id)_IDE_authorizeTestSessionWithProcessID:(NSNumber *)arg1;
- (id)_IDE_initiateControlSessionWithCapabilities:(XCTCapabilities *)arg1;
- (id)_IDE_initiateControlSessionWithProtocolVersion:(NSNumber *)arg1;
- (id)_IDE_initiateControlSessionForTestProcessID:(NSNumber *)arg1 protocolVersion:(NSNumber *)arg2;
- (id)_IDE_initiateControlSessionForTestProcessID:(NSNumber *)arg1;
@end

#endif
