#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 150000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 160000

#import "Xcode_13_0_XCTestCore_CDStructures.h"
#import "Xcode_13_0_SharedHeader.h"
#import "Xcode_13_0_XCTSymbolInfoProviding.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTOutOfProcessSymbolicationService : NSObject <XCTSymbolInfoProviding>
{
    _Bool _releaseOnDealloc;
    NSArray *_symbolicators;
    CDStruct_37ea9563 _symbolicationFunctions;
}

+ (id)recursivelyFindDSYMsInDirectory:(id)arg1;
@property(readonly) _Bool releaseOnDealloc; // @synthesize releaseOnDealloc=_releaseOnDealloc;
@property(readonly) CDStruct_37ea9563 symbolicationFunctions; // @synthesize symbolicationFunctions=_symbolicationFunctions;
@property(copy) NSArray *symbolicators; // @synthesize symbolicators=_symbolicators;
- (id)symbolInfoForImageOffset:(unsigned long long)arg1 forImageWithPath:(id)arg2 andArch:(id)arg3 error:(id *)arg4;
- (id)symbolInfoForImageOffset:(unsigned long long)arg1 inImageWithUUID:(id)arg2 error:(id *)arg3;
- (id)symbolInfoForAddressInCurrentProcess:(unsigned long long)arg1 error:(id *)arg2;
- (id)initWithDSYMURLs:(id)arg1 includeSharedCache:(_Bool)arg2 skipMalformedDSYMs:(_Bool)arg3 skippedDSYMURLs:(id *)arg4 error:(id *)arg5;
- (id)initWithDSYMURLs:(id)arg1 includeSharedCache:(_Bool)arg2 symbolicationFunctions:(CDStruct_37ea9563)arg3 skipMalformedDSYMs:(_Bool)arg4 skippedDSYMURLs:(id *)arg5 error:(id *)arg6;
- (void)dealloc;
- (id)initWithSymbolicators:(id)arg1 releaseOnDealloc:(_Bool)arg2 symbolicationFunctions:(CDStruct_37ea9563)arg3;

// Remaining properties

@end

#endif