#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 120000

#import "Xcode10_XCTest_CDStructures.h"
#import "Xcode10_SharedHeader.h"
#import "Xcode10_XCElementSnapshot.h"
#import "Xcode10_XCUIElementSnapshot.h"

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCElementSnapshot (XCUIElementSnapshot) <XCUIElementSnapshot>
@property(readonly, copy) NSDictionary *dictionaryRepresentation;

// Remaining properties
@property(readonly) NSArray *children;
@property(readonly) unsigned long long elementType;
@property(readonly, getter=isEnabled) _Bool enabled;
@property(readonly) struct CGRect frame;
@property(readonly) long long horizontalSizeClass;
@property(readonly) NSString *identifier;
@property(readonly, copy) NSString *label;
@property(readonly) NSString *placeholderValue;
@property(readonly, getter=isSelected) _Bool selected;
@property(readonly, copy) NSString *title;
@property(readonly) id value;
@property(readonly) long long verticalSizeClass;
@end

#endif