excluded:
  # Cocoapods
  - 'Tests/Pods'
  - 'Demos/UiTestsDemo/Pods'
  - 'Frameworks/BuiltinIpc/OsxDemo/Pods'
  
  # Build
  - 'Frameworks/BuiltinIpc/OsxDemo/build'
  - 'ci/swift/.build'
  - '.build'

disabled_rules:
  - line_length # "ignores_interpolated_strings" doesn't work for multiline literals.
  - opening_brace # I don't like it
  - trailing_whitespace # TODO: Enable
  - colon # I don't like how it works with multiple inheritance/conformance
  - void_return # I like `()`
  - unneeded_parentheses_in_closure_argument # Has bug with { () -> () in ... }, but sometimes I want to help Swift complile faster.
  - redundant_nil_coalescing # I want to convert double optionals to single optionals with `x ?? nil`. TODO: Maybe to add a function.
  - identifier_name # i don't like those limits. TODO: Enable partially, configure
  - type_name # same as with identifier_name
  - todo # i fix todos sometimes
  - operator_whitespace # i don't like this rule
  - function_parameter_count # i like such functions in tests...
  - legacy_hashing # TODO: Do we support Swift < 4.2?
  - no_space_in_method_call # Bugged since 2022.08.09 (about 1000 false positives)
  
  # Remove after updating SwiftLint and Xcode and fixing every warning
  - implicit_getter # this rule is triggering only in Xcode 11.4.1 and not in Xcode 11.3.1 and only in old SwiftLint. New swiftlint rules are for Xcode 11.4.1, which is not fully supported
  
opt_in_rules:
  - array_init
  - block_based_kvo
  - contains_over_first_not_nil
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - comma
  - compiler_protocol_init
  - control_statement
  - discarded_notification_center_observer
  - discouraged_object_literal
  - discouraged_direct_init
  - duplicate_imports
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - explicit_init
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - generic_type_name
  - fatal_error_message
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - line_length
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nslocalizedstring_key
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_void_return
  - return_arrow_whitespace
  - statement_position
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - trailing_newline
  - trailing_semicolon
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - weak_delegate

# Rule configurations

array_init:
  severity: error

block_based_kvo:
  severity: error

contains_over_first_not_nil:
  severity: error

class_delegate_protocol:
  severity: error

closing_brace:
  severity: error

closure_end_indentation:
  severity: error

closure_spacing:
  severity: error

comma:
  severity: error

compiler_protocol_init:
  severity: error

discouraged_direct_init:
  severity: error

discouraged_object_literal:
  severity: error

control_statement:
  severity: error

discarded_notification_center_observer:
  severity: error

duplicate_imports:
  severity: error

empty_count:
  severity: error

empty_enum_arguments:
  severity: error

empty_parameters:
  severity: error

empty_parentheses_with_trailing_closure:
  severity: error

empty_string:
  severity: error

empty_xctest_method:
  severity: error

first_where:
  severity: error

explicit_init:
  severity: error

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: error

generic_type_name:
  min_length:
    warning: 1
    error: 0
  max_length:
    warning: 50
    error: 70

fatal_error_message:
  severity: error

implicit_getter:
  severity: error

implicit_return:
  severity: error

implicitly_unwrapped_optional:
  severity: error

last_where:
  severity: error

leading_whitespace:
  severity: error

legacy_cggeometry_functions:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

line_length:
  warning: 220
  error: 230
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true
  ignores_function_declarations: false

lower_acl_than_parent:
  severity: error

mark:
  severity: error

modifier_order:
  severity: error

multiline_arguments:
  severity: error

multiline_parameters:
  severity: error

multiple_closures_with_trailing_closure:
  severity: error

nesting:
  type_level:
    warning: 2
    error: 2
  statement_level:
    warning: 5
    error: 5
    
nslocalizedstring_key:
  severity: error

operator_usage_whitespace:
  severity: error

overridden_super_call:
  severity: error

pattern_matching_keywords:
  severity: error

private_outlet:
  severity: error

prohibited_super_call:
  severity: error

protocol_property_accessors_order:
  severity: error

redundant_discardable_let:
  severity: error

redundant_nil_coalescing:
  severity: error

redundant_optional_initialization:
  severity: error

redundant_set_access_control:
  severity: error

redundant_void_return:
  severity: error

return_arrow_whitespace:
  severity: error

statement_position:
  severity: error

switch_case_alignment:
  severity: error

switch_case_on_newline:
  severity: error

syntactic_sugar:
  severity: error

trailing_newline:
  severity: error

trailing_semicolon:
  severity: error

unneeded_break_in_switch:
  severity: error

unneeded_parentheses_in_closure_argument:
  severity: error

unused_closure_parameter:
  severity: error

unused_enumerated:
  severity: error

unused_optional_binding:
  severity: error

vertical_parameter_alignment:
  severity: error

vertical_parameter_alignment_on_call:
  severity: error

vertical_whitespace:
  severity: error

weak_delegate:
  severity: error
