#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 160000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 170000

#import "Xcode_14_0_XCUIAutomation_CDStructures.h"
#import "Xcode_14_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@class XCAccessibilityElement, XCUIApplication, XCUIElement;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCUIAccessibilityAuditIssue : NSObject
{
    NSString *_longDescription;
    NSString *_shortDescription;
    XCAccessibilityElement *_axElement;
    XCUIApplication *_application;
}

@property(readonly, nonatomic) XCUIApplication *application; // @synthesize application=_application;
@property(readonly, nonatomic) XCAccessibilityElement *axElement; // @synthesize axElement=_axElement;
@property(copy, nonatomic) NSString *shortDescription; // @synthesize shortDescription=_shortDescription;
@property(copy, nonatomic) NSString *longDescription; // @synthesize longDescription=_longDescription;
- (id)description;
@property(readonly, nonatomic) XCUIElement *element; // @dynamic element;
- (id)initWithResult:(id)arg1 forApplication:(id)arg2;

@end

#endif