require './PodfileUtils'

project 'Tests.xcodeproj'
workspace 'Tests.xcworkspace'

platform :ios, :deployment_target => '9.0'

use_frameworks!

def ui_tests_pods
  pod 'MixboxTestsFoundation', :path => '..'
  pod 'MixboxUiTestsFoundation', :path => '..'
  pod 'MixboxArtifacts', :path => '..'
  pod 'SwiftyJSON', '3.1.4', :inhibit_warnings => true
end

def application_testability_and_blackbox_testing_common_pods
  pod 'MixboxIpc', :path => '..'
  pod 'MixboxIpcCommon', :path => '..'
  pod 'MixboxUiKit', :path => '..'
  pod 'MixboxBuiltinIpc', :path => '..'
end

def application_testability_pods
  application_testability_and_blackbox_testing_common_pods
  
  # pod 'GCDWebServer'
  # pod 'SBTUITestTunnel/Server'
  pod 'MixboxTestability', :path => '..'
  pod 'MixboxIpcSbtuiHost', :path => '..'
  pod 'MixboxInAppServices', :path => '..'
end

def blackbox_tests_pods
  ui_tests_pods
  application_testability_and_blackbox_testing_common_pods

  pod 'CocoaImageHashing', '1.6.1', :inhibit_warnings => true
  pod 'SBTUITestTunnel/Client', :inhibit_warnings => true
  pod 'MixboxIpcSbtuiClient', :path => '..'
  pod 'MixboxIpcClients', :path => '..'
  pod 'MixboxReporting', :path => '..'
  pod 'MixboxFoundation', :path => '..'
  pod 'MixboxXcuiDriver', :path => '..'
  pod 'SimulatorRemoteNotifications', '~> 0.0.3', :inhibit_warnings => true
end

### TARGETS

target 'Tests' do
  application_testability_pods
end

target 'XcuiTests' do
  inherit! :search_paths

  blackbox_tests_pods
end

target 'UnitTests' do
  inherit! :search_paths

  ui_tests_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        config.build_settings['ENABLE_BITCODE'] = 'NO' # To support testing on devices
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-D', 'MIXBOX_ENABLE_IN_APP_SERVICES', '-Onone']
        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'MIXBOX_ENABLE_IN_APP_SERVICES=1', 'ENABLE_UITUNNEL=1']
      end
    end
  end
end
