require_relative '../cocoapods/lock_patcher'
require_relative '../cocoapods/repo'
require_relative '../cocoapods/software_versions'
require_relative '../cocoapods/patch_xcconfigs_toolchain_dir'
require_relative '../cocoapods/patch_deployment_target'

ENV["MIXBOX_SET_VERSION_TO_001"] = "true"

project 'Tests.xcodeproj'
workspace 'Tests.xcworkspace'

use_frameworks!

@mixbox = Devpods::Repo.new(
    'ssh://git@github.com:avito-tech/Mixbox.git',
    lambda { |name, hash|
      local_hash = hash.clone
      local_hash[:inhibit_warnings] = false
      local_hash[:configurations] = ['Debug']
      pod name, local_hash
    }
)
@mixbox.local_path_value = '..'

sourcery = Devpods::Repo.new(
    'https://github.com/avito-tech/Sourcery.git',
    lambda { |name, hash|
      local_hash = hash.clone
      local_hash[:inhibit_warnings] = false
      local_hash[:configurations] = ['Debug']
      pod name, local_hash
    }
)
sourcery.commit_value = '0564feccdc8fade6c68376bdf7f8dab9b79863fe'
sourcery.branch_value = 'avito'
sourcery.local_path_env = 'MIXBOX_SOURCERY_LOCAL_PATH'

def tests_ipc_pods
  pod 'TestsIpc', :path => 'Frameworks/TestsIpc'
end

def tests_foundation_pod()
  @mixbox.pod 'MixboxTestsFoundation'
  pod 'SQLite.swift', :inhibit_warnings => true
end

def execute_shell_or_raise(shell_command)
  puts "Executing #{shell_command}..."
  system(shell_command, { :out => File::NULL, :err => File::NULL }) or raise "Shell command failed: #{shell_command}"
end
 
### TARGETS

target 'TestedApp' do
  platform :ios, $mixbox_ios_version
  
  @mixbox.pod 'MixboxInAppServices'

  tests_ipc_pods
end

target 'FakeSettingsApp' do
  platform :ios, $mixbox_ios_version
  
  @mixbox.pod 'MixboxFakeSettingsAppMain'
end

target 'GrayBoxUiTests' do
  platform :ios, $mixbox_ios_version
  
  # Code being tested:
  @mixbox.pod 'MixboxGray'
  tests_foundation_pod
  @mixbox.pod 'MixboxLinkXCTAutomationSupport'
  
  # Helpers:
  @mixbox.pod 'MixboxStubbing'
  @mixbox.pod 'MixboxMocksRuntime'
  
  tests_ipc_pods
end

target 'BlackBoxUiTests' do
  platform :ios, $mixbox_ios_version
  
  # Code being tested:
  @mixbox.pod 'MixboxBlack'
  tests_foundation_pod
  @mixbox.pod 'MixboxLinkXCTAutomationSupport'
  
  # Helpers:
  @mixbox.pod 'MixboxMocksRuntime'
  @mixbox.pod 'MixboxStubbing'

  tests_ipc_pods
end
  
target 'UnitTests' do
  platform :ios, $mixbox_ios_version
  
  @mixbox.pod_all_ios
  tests_foundation_pod
  @mixbox.pod 'MixboxLinkXCTAutomationSupport'
  
  tests_ipc_pods # A kludge to access Singletons unrelated to IPC from TestsIpc (nice!).
end

target 'OsxUnitTests' do
  platform :osx, $mixbox_osx_version

  sourcery.pod 'SourceryFramework'
  sourcery.pod 'SourceryRuntime'
  @mixbox.pod_all_osx
end

target 'HostedAppLogicTests' do
  platform :ios, $mixbox_ios_version
  
  @mixbox.pod_all_ios
  tests_foundation_pod
  @mixbox.pod 'MixboxLinkXCTAutomationSupport'
  
  tests_ipc_pods # A kludge to access Singletons unrelated to IPC from TestsIpc (nice!).
end

target 'Lint' do
  platform :ios, $mixbox_ios_version
  
  pod 'SwiftLint', '0.36.0', :inhibit_warnings => true # TODO: Update.
end

pre_install do |installer|
  # Xcode with new build system requires all files to be added to ".xcodeproj" before
  # building the project (even if source files are generated before being compiled).
  # So this will create files (and also generate proper code)
  execute_shell_or_raise("'#{__dir__}/Scripts/warm_up_code_generation'")
  execute_shell_or_raise("'#{__dir__}/GrayBoxUiTests/Mocks/generate_mocks'")
  execute_shell_or_raise("'#{__dir__}/UnitTests/Mocks/generate_mocks'")
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name != 'MixboxMocksGeneration'
        if config.name == 'Debug'
          config.build_settings['ENABLE_BITCODE'] = 'NO' # To support testing on devices
          config.build_settings['ENABLE_TESTABILITY'] = 'YES' # To support @testable import
          config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-D', 'MIXBOX_ENABLE_ALL_FRAMEWORKS', '-Onone']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'MIXBOX_ENABLE_ALL_FRAMEWORKS=1']
        end
      end
    end
    
    remove_default_imports_from_target(target)
  end
  
  inhibit_update_to_recommended_settings_warning(installer)
  patch_to_be_able_to_run_executable(installer)

  # Fix for cocoapods lower than 1.13 on xcode 15
  patch_xcconfigs_toolchain_dir(installer)
end

at_exit do
  inhibit_pod_deployment_target_warning()
end

# Inhibits this warning in Xcode:
# ```
# Update to recommended settings
# ```
def inhibit_update_to_recommended_settings_warning(installer)
  # For example, for Xcode 14.2 the version is 1420
  far_future_xcode_version = 9999
  
  installer.pods_project.root_object.attributes['LastSwiftMigration'] = far_future_xcode_version
  installer.pods_project.root_object.attributes['LastSwiftUpdateCheck'] = far_future_xcode_version
  installer.pods_project.root_object.attributes['LastUpgradeCheck'] = far_future_xcode_version

  shared_data_dir = Xcodeproj::XCScheme.user_data_dir(installer.pods_project.path)
  Dir["#{shared_data_dir}/*.xcscheme"].each do |scheme_path|
    scheme = Xcodeproj::XCScheme.new scheme_path
    scheme.doc.root.attributes['LastUpgradeVersion'] = far_future_xcode_version
    scheme.save!
  end
end

def patch_to_be_able_to_run_executable(installer)
  project = Xcodeproj::Project.open('Tests.xcodeproj')
  
  project.native_targets.each do |native_target|
    if native_target.name == 'MocksGenerator'
      native_target.build_configurations.each do |config|
        config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = '$(inherited) @executable_path/../Frameworks @loader_path/Frameworks'
        
        installer.pods_project.targets.each do |pod_target|
          # For each pod, add the framework path to LD_RUNPATH_SEARCH_PATHS
          framework_name = pod_target.name
          search_path = "@executable_path/#{framework_name}/"
          config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = config.build_settings['LD_RUNPATH_SEARCH_PATHS'] + " #{search_path}"
        end
      end
    end
  end
  
  project.save
end

def remove_default_imports_from_target(target)
    # It doesn't work for MixboxBlack & MixboxTestsFoundation targets. Errors are like `Unknown type name 'XCEventGenerator'`
  if ['MixboxBlack', 'MixboxTestsFoundation'].include?(target.name)
    return
  end
  
  dir = "#{__dir__}/Pods/Target Support Files/#{target.name}"
  
  remove_default_imports_from_file("#{dir}/#{target.name}-umbrella.h")
  remove_default_imports_from_file("#{dir}/#{target.name}-prefix.pch")
end

def remove_default_imports_from_file(file_path)
  if File.file?(file_path)
    text = File.read(file_path)
    
    new_defines = '#ifndef MIXBOX_EXPORT
#if defined(__cplusplus)
#define MIXBOX_EXPORT extern "C"
#else
#define MIXBOX_EXPORT extern
#endif
#endif'

    # iOS
    text = text.gsub(old_defines('UIKit'), new_defines)
    # OSX
    text = text.gsub(old_defines('Cocoa'), new_defines)
    text = text.gsub('FOUNDATION_EXPORT', 'MIXBOX_EXPORT')

    File.open(file_path, "w") { |file| file.puts text }
  end
end

def old_defines(framework)
  "#ifdef __OBJC__
#import <#{framework}/#{framework}.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern \"C\"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif"
end
