require_relative 'PodfileUtils/lock_patcher'
require_relative 'PodfileUtils/repo'

project 'Tests.xcodeproj'
workspace 'Tests.xcworkspace'

platform :ios, :deployment_target => '9.0'

use_frameworks!
inhibit_all_warnings!

mixbox = Devpods::Repo.new(
    'ssh://git@github.com:avito-tech/Mixbox.git',
    lambda { |name, hash|
      local_hash = hash.clone
      local_hash[:inhibit_warnings] = false
      local_hash[:configurations] = ['Debug']
      pod name, local_hash
    }
)
mixbox.local_path_value = '..'

def tests_ipc_pods
  pod 'TestsIpc', :path => 'Frameworks/TestsIpc'
end

# TODO: Support mock generation for every test target
def tests_testing_helpers
  pod 'Cuckoo', :git => 'https://github.com/avito-tech/Cuckoo', :branch => 'avito20200410', :inhibit_warnings => true
end

def logic_tests_pods(mixbox_repo)
  mixbox_repo.all_pods.each { |name|
    mixbox_repo.pod name
  }

  pod 'SBTUITestTunnel/Client', '3.0.6', :inhibit_warnings => true
  pod 'SBTUITestTunnel/Server', '3.0.6', :inhibit_warnings => true
  tests_testing_helpers
end
 
### TARGETS

target 'TestedApp' do
  mixbox.pod 'MixboxInAppServices'
  mixbox.pod 'MixboxIpcSbtuiHost'
  pod 'SBTUITestTunnel/Server', '3.0.6', :inhibit_warnings => true

  tests_ipc_pods
end

target 'FakeSettingsApp' do
  mixbox.pod 'MixboxFakeSettingsAppMain'
end

target 'GrayBoxUiTests' do
  mixbox.pod 'MixboxGray'
  mixbox.pod 'MixboxStubbing'
  
  tests_testing_helpers
  tests_ipc_pods
end

target 'BlackBoxUiTests' do
  mixbox.pod 'MixboxBlack'
  mixbox.pod 'MixboxIpcSbtuiClient'
  pod 'SBTUITestTunnel/Client', '3.0.6', :inhibit_warnings => true

  tests_testing_helpers
  tests_ipc_pods
end
  
target 'UnitTests' do
  logic_tests_pods mixbox
  tests_ipc_pods # A kludge to access Singletons unrelated to IPC from TestsIpc (nice!).
end

target 'HostedAppLogicTests' do
  logic_tests_pods mixbox
  tests_ipc_pods # A kludge to access Singletons unrelated to IPC from TestsIpc (nice!).
end

target 'Lint' do
  pod 'SwiftLint', :inhibit_warnings => true
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        config.build_settings['ENABLE_BITCODE'] = 'NO' # To support testing on devices
        config.build_settings['ENABLE_TESTABILITY'] = 'YES' # To support @testable import
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-D', 'MIXBOX_ENABLE_IN_APP_SERVICES', '-Onone']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'MIXBOX_ENABLE_IN_APP_SERVICES=1', 'ENABLE_UITUNNEL=1']
      end
    end
    
    remove_uikit_import_from_target(target)
  end
end

def remove_uikit_import_from_target(target)
  if ['MixboxBlack', 'MixboxTestsFoundation'].include?(target.name)
    # It doesn't work for these targets. Errors are like `Unknown type name 'XCEventGenerator'`
    return
  end
  
  dir = "#{__dir__}/Pods/Target Support Files/#{target.name}"
  
  remove_uikit_import_from_file("#{dir}/#{target.name}-umbrella.h")
  remove_uikit_import_from_file("#{dir}/#{target.name}-prefix.pch")
end

def remove_uikit_import_from_file(file_path)
  if File.file?(file_path)
    text = File.read(file_path)
    
    new_defines = '#ifndef MIXBOX_EXPORT
#if defined(__cplusplus)
#define MIXBOX_EXPORT extern "C"
#else
#define MIXBOX_EXPORT extern
#endif
#endif'

    old_defines = '#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif'


    text = text.gsub(old_defines, new_defines)
    text = text.gsub('FOUNDATION_EXPORT', 'MIXBOX_EXPORT')

    File.open(file_path, "w") { |file| file.puts text }
  end
end