#!/bin/bash

set -ueo pipefail

script_root=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "${script_root}/../../.." && pwd)

source "$REPO_ROOT/Tests/Scripts/mock_generation.sh"

# DSL

apply_mocks() {
    module "MixboxInAppServices"
    mock "AllMethodsWithUniqueImplementationAccessibilityLabelSwizzlerFactory"
    mock "EnhancedAccessibilityLabelMethodSwizzler"
    mock "ObjcMethodsWithUniqueImplementationProvider"
}

generate "GrayBoxUiTests" "${REPO_ROOT}/Tests/GrayBoxUiTests/Mocks"
