#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 140000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 150000

#import "Xcode_12_0_XCTest_CDStructures.h"
#import "Xcode_12_0_SharedHeader.h"
#import "Xcode_12_0_XCTestExpectationDelegate.h"
#import <XCTest/XCTestExpectation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTCompoundExpectation : XCTestExpectation <XCTestExpectationDelegate>
{
    unsigned long long _logicalType;
    NSArray *_subexpectations;
}

@property(readonly, copy) NSArray *subexpectations; // @synthesize subexpectations=_subexpectations;
@property(readonly) unsigned long long logicalType; // @synthesize logicalType=_logicalType;
- (void)didFulfillExpectation:(id)arg1;
- (void)cleanup;
- (_Bool)_queue_validateSubexpectationsFulfillment;
- (void)_updateFulfilledState;
- (void)dealloc;
- (id)initWithLogicalType:(unsigned long long)arg1 subexpectations:(id)arg2;

// Remaining properties

@end

#endif