#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 140000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 150000

#import "Xcode_12_0_XCTest_CDStructures.h"
#import "Xcode_12_0_SharedHeader.h"
#import <Foundation/Foundation.h>
#import <XCTest/XCTestExpectation.h>

@protocol XCTestExpectationDelegate;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTestExpectation ()
{
    _Bool _fulfilled;
    _Bool _hasBeenWaitedOn;
    _Bool _inverted;
    _Bool _assertForOverFulfill;
    id <XCTestExpectationDelegate> _delegate;
    unsigned long long _fulfillmentToken;
    NSArray *_fulfillCallStackReturnAddresses;
    unsigned long long _expectedFulfillmentCount;
    NSString *_expectationDescription;
    unsigned long long _numberOfFulfillments;
    unsigned long long _creationToken;
    NSArray *_creationCallStackReturnAddresses;
}

+ (id)expectationWithDescription:(id)arg1;
+ (id)compoundOrExpectationWithSubexpectations:(id)arg1;
+ (id)compoundAndExpectationWithSubexpectations:(id)arg1;
@property(readonly, copy) NSArray *creationCallStackReturnAddresses; // @synthesize creationCallStackReturnAddresses=_creationCallStackReturnAddresses;
@property(readonly) unsigned long long creationToken; // @synthesize creationToken=_creationToken;
@property unsigned long long numberOfFulfillments; // @synthesize numberOfFulfillments=_numberOfFulfillments;
- (void)cleanup;
@property _Bool hasBeenWaitedOn; // @synthesize hasBeenWaitedOn=_hasBeenWaitedOn;
- (void)on_queue_setHasBeenWaitedOn:(_Bool)arg1;
@property __weak id <XCTestExpectationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSArray *fulfillCallStackReturnAddresses; // @synthesize fulfillCallStackReturnAddresses=_fulfillCallStackReturnAddresses;
@property(readonly) _Bool on_queue_fulfilled;
@property(readonly) _Bool fulfilled; // @synthesize fulfilled=_fulfilled;
@property _Bool hasInverseBehavior;
@property(readonly) _Bool on_queue_isInverted;
@property(nonatomic) unsigned long long fulfillmentCount;
@property(readonly) unsigned long long on_queue_fulfillmentToken;
@property(readonly) unsigned long long fulfillmentToken; // @synthesize fulfillmentToken=_fulfillmentToken;
- (_Bool)_queue_fulfillWithCallStackReturnAddresses:(id)arg1;
- (void)fulfill;
- (id)description;

- (id)init;

@end

#endif