#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 140000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 150000

#import "Xcode_12_0_XCTest_CDStructures.h"
#import "Xcode_12_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@class UIImage;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTImage : NSObject <NSCopying>
{
    UIImage *_platformImage;
    NSData *_originalData;
    NSString *_name;
    double _scale;
}

+ (id)_dataForImage:(id)arg1 uti:(id)arg2 compressionQuality:(double)arg3;
+ (id)_dataForImage:(id)arg1 quality:(long long)arg2;
+ (double)_scaleForImage:(id)arg1;
+ (id)UTIForQuality:(long long)arg1;
+ (double)compressionQualityForQuality:(long long)arg1;
+ (id)emptyImageWithSize:(struct CGSize)arg1;
@property(readonly) double scale; // @synthesize scale=_scale;
@property(copy) NSString *name; // @synthesize name=_name;
@property(copy) NSData *originalData; // @synthesize originalData=_originalData;
@property(copy) UIImage *platformImage; // @synthesize platformImage=_platformImage;
- (id)debugQuickLookObject;
- (void)_ensureImage;
- (id)attachment;
@property(readonly, copy) UIImage *image;
@property(readonly, copy) NSData *data;
- (id)dataWithQuality:(long long)arg1;
- (id)initWithData:(id)arg1 scale:(double)arg2;
- (id)initWithImage:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

#endif