#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 140000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 150000

#import "Xcode_12_0_XCTest_CDStructures.h"
#import "Xcode_12_0_SharedHeader.h"
#import <Foundation/Foundation.h>
#import <XCTest/XCTIssue.h>

@class XCTSourceCodeContext;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTIssue ()
{
    // Error parsing type: {atomic_flag="_Value"AB}, name: _failureBreakPointCalled
    _Bool _didInterruptTest;
    _Bool _shouldInterruptTest;
    long long _type;
    NSString *_compactDescription;
    NSString *_detailedDescription;
    XCTSourceCodeContext *_sourceCodeContext;
    NSError *_associatedError;
    NSArray *_attachments;
    NSDate *_timestamp;
}

+ (_Bool)supportsSecureCoding;
+ (id)issueWithType:(long long)arg1 compactDescription:(id)arg2 callStackAddresses:(id)arg3 filePath:(id)arg4 lineNumber:(long long)arg5;
+ (id)issueWithException:(id)arg1;
+ (id)issueWithType:(long long)arg1 compactDescription:(id)arg2 associatedError:(id)arg3;
@property _Bool shouldInterruptTest; // @synthesize shouldInterruptTest=_shouldInterruptTest;
@property _Bool didInterruptTest; // @synthesize didInterruptTest=_didInterruptTest;
// Error parsing type for property failureBreakPointCalled:
// Property attributes: T{atomic_flag=AB},V_failureBreakPointCalled

@property(copy) NSDate *timestamp; // @synthesize timestamp=_timestamp;
- (_Bool)matchesLegacyPropertiesOfIssue:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly) _Bool isLegacyExpectedFailure;
@property(readonly) _Bool isFailure;
- (id)description;
- (void)_updateAttachmentsTimestamps;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

#endif