#ifdef MIXBOX_ENABLE_IN_APP_SERVICES

typedef NS_CLOSED_ENUM(NSUInteger, TestabilityElementType) {
    TestabilityElementType_Other = 0,
    TestabilityElementType_Application,
    TestabilityElementType_Group,
    TestabilityElementType_Window,
    TestabilityElementType_Sheet,
    TestabilityElementType_Drawer,
    TestabilityElementType_Alert,
    TestabilityElementType_Dialog,
    TestabilityElementType_Button,
    TestabilityElementType_RadioButton,
    TestabilityElementType_RadioGroup,
    TestabilityElementType_CheckBox,
    TestabilityElementType_DisclosureTriangle,
    TestabilityElementType_PopUpButton,
    TestabilityElementType_ComboBox,
    TestabilityElementType_MenuButton,
    TestabilityElementType_ToolbarButton,
    TestabilityElementType_Popover,
    TestabilityElementType_Keyboard,
    TestabilityElementType_Key,
    TestabilityElementType_NavigationBar,
    TestabilityElementType_TabBar,
    TestabilityElementType_TabGroup,
    TestabilityElementType_Toolbar,
    TestabilityElementType_StatusBar,
    TestabilityElementType_Table,
    TestabilityElementType_TableRow,
    TestabilityElementType_TableColumn,
    TestabilityElementType_Outline,
    TestabilityElementType_OutlineRow,
    TestabilityElementType_Browser,
    TestabilityElementType_CollectionView,
    TestabilityElementType_Slider,
    TestabilityElementType_PageIndicator,
    TestabilityElementType_ProgressIndicator,
    TestabilityElementType_ActivityIndicator,
    TestabilityElementType_SegmentedControl,
    TestabilityElementType_Picker,
    TestabilityElementType_PickerWheel,
    TestabilityElementType_Switch,
    TestabilityElementType_Toggle,
    TestabilityElementType_Link,
    TestabilityElementType_Image,
    TestabilityElementType_Icon,
    TestabilityElementType_SearchField,
    TestabilityElementType_ScrollView,
    TestabilityElementType_ScrollBar,
    TestabilityElementType_StaticText,
    TestabilityElementType_TextField,
    TestabilityElementType_SecureTextField,
    TestabilityElementType_DatePicker,
    TestabilityElementType_TextView,
    TestabilityElementType_Menu,
    TestabilityElementType_MenuItem,
    TestabilityElementType_MenuBar,
    TestabilityElementType_MenuBarItem,
    TestabilityElementType_Map,
    TestabilityElementType_WebView,
    TestabilityElementType_IncrementArrow,
    TestabilityElementType_DecrementArrow,
    TestabilityElementType_Timeline,
    TestabilityElementType_RatingIndicator,
    TestabilityElementType_valueIndicator,
    TestabilityElementType_SplitGroup,
    TestabilityElementType_Splitter,
    TestabilityElementType_RelevanceIndicator,
    TestabilityElementType_ColorWell,
    TestabilityElementType_HelpTag,
    TestabilityElementType_Matte,
    TestabilityElementType_DockItem,
    TestabilityElementType_Ruler,
    TestabilityElementType_RulerMarker,
    TestabilityElementType_Grid,
    TestabilityElementType_LevelIndicator,
    TestabilityElementType_Cell,
    TestabilityElementType_LayoutArea,
    TestabilityElementType_LayoutItem,
    TestabilityElementType_Handle,
    TestabilityElementType_Stepper,
    TestabilityElementType_Tab,
    TestabilityElementType_TouchBar,
    TestabilityElementType_StatusItem
};

#else

// Swift-to-Objective-C bridging doesn't support modification with #ifdef.
// I don't know a way to define MIXBOX_ENABLE_IN_APP_SERVICES while bridging header is being made.

typedef int TestabilityElementType;

#endif
