#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCUIAutomation_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@class XCTAttachmentFuture, XCTImage, XCTScreenshotRequest;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCUILocalDeviceScreenshotIPCInterface <NSObject>
@property(readonly, nonatomic) _Bool supportsHEICImageEncoding;
@property(readonly, nonatomic) _Bool useLegacyScreenshotPath;
- (void)requestScreenshotAttachmentWithRequest:(XCTScreenshotRequest *)arg1 withReply:(void (^)(XCTAttachmentFuture *, NSError *))arg2;
- (void)requestScreenshotWithRequest:(XCTScreenshotRequest *)arg1 withReply:(void (^)(XCTImage *, NSError *))arg2;
@end

#endif
