#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCUIAutomation_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import "Xcode_15_0_XCUIApplicationProcessManaging.h"
#import <Foundation/Foundation.h>

@protocol XCUIPlatformApplicationServicesProviding;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

__attribute__((visibility("hidden")))
@interface XCUIPlatformApplicationManager : NSObject <XCUIApplicationProcessManaging>
{
    id <XCUIPlatformApplicationServicesProviding> _platformApplicationServicesProvider;
}

+ (_Bool)_shouldRetryForLaunchError:(id)arg1;
@property(readonly) id <XCUIPlatformApplicationServicesProviding> platformApplicationServicesProvider; // @synthesize platformApplicationServicesProvider=_platformApplicationServicesProvider;
- (void)openURL:(id)arg1 usingApplication:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)openDefaultApplicationForURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)launchProcessWithPath:(id)arg1 bundleID:(id)arg2 arguments:(id)arg3 environmentVariables:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (id)initWithPlatformApplicationServicesProvider:(id)arg1;

// Remaining properties

@end

#endif