#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 150000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 160000

#import "Xcode_13_0_XCTAutomationSupport_CDStructures.h"
#import "Xcode_13_0_SharedHeader.h"
#import "Xcode_13_0_XCTCapabilitiesProviding.h"
#import <Foundation/Foundation.h>

@protocol XCTMatchingElementIterator;

@class XCElementSnapshot, XCTCapabilities;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTElementSetTransformer <NSObject, NSCopying, XCTCapabilitiesProviding>
@property(readonly, copy) NSSet *elementTypes;
@property _Bool stopsOnFirstMatch;
@property(readonly) _Bool supportsAttributeKeyPathAnalysis;
@property(copy) NSString *transformationDescription;
- (NSSet *)requiredKeyPathsOrError:(id *)arg1;
- (_Bool)canBeRemotelyEvaluatedWithCapabilities:(XCTCapabilities *)arg1;
- (id <XCTMatchingElementIterator>)iteratorForInput:(XCElementSnapshot *)arg1;
- (NSOrderedSet *)transform:(NSOrderedSet *)arg1 relatedElements:(id *)arg2;
@end

#endif
