#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 140000

#import "Xcode_11_0_XCTAutomationSupport_CDStructures.h"
#import "Xcode_11_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@protocol XCTRuntimeIssue;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTRuntimeIssue <NSObject, NSSecureCoding>
+ (NSString *)capability;
@property(readonly) unsigned long long aggregationHash;
@property(readonly) NSString *detailedDescription;
@property(readonly) NSString *shortDescription;
- (_Bool)isEqualForAggregationWith:(id <XCTRuntimeIssue>)arg1;
@end

#endif
