project 'OversimplifiedDemo.xcodeproj'
workspace 'OversimplifiedDemo.xcworkspace'

platform :ios, :deployment_target => '9.0'

inhibit_all_warnings!
use_frameworks!

target 'OversimplifiedDemo' do
  pod 'MixboxInAppServices', '0.2.3'
  
  pod 'SQLite.swift', '0.11.5' # Xcode 10.2: '0.12.0' (lower also suits)
end

target 'OversimplifiedDemoUITests' do
  pod 'MixboxXcuiDriver', '0.2.3'
end
  
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        # NOTE: You may want to add add '-Onone' for your debug builds so they will be compiled faster.
        
        # MIXBOX_ENABLE_IN_APP_SERVICES enables code for testing. You should not include that code in release builds.
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-D', 'MIXBOX_ENABLE_IN_APP_SERVICES']
        
        # ENABLE_UITUNNEL is a same thing, but for SBTUITestTunnel library. We're planning to stop using it. If there is no such dependency now, remove this definition.
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ENABLE_UITUNNEL=1', 'MIXBOX_ENABLE_IN_APP_SERVICES=1']
      end
    end
  end
end
