/* Generated by RuntimeBrowser
 Image: /System/Library/Frameworks/CoreLocation.framework/CoreLocation
 */

#import <CoreLocation/CoreLocation.h>

@interface CLLocationManager (Private)
+ (CLAuthorizationStatus)authorizationStatusForBundleIdentifier:(id)arg1;
+ (void)setAuthorizationStatusByType:(CLAuthorizationStatus)status forBundleIdentifier:(NSString *)bundleId;
+ (BOOL)shutdownDaemon;
@end
