#!/bin/bash

# Required environment:
# MIXBOX_PUSHSPEC_VERSION (e.g. "0.0.1")
# MIXBOX_PUSHSPEC_ORIGIN (e.g. "origin")

for include in "$(dirname $0)/../include/"*; do source "$include"; done

pod cache clean --all
MIXBOX_PUSHSPEC_STYLE=debug "$MIXBOX_CI_REPO_ROOT/push_specs"
LOCAL_SPEC_REPO=true pod update
