#!/bin/bash

# For compatibility with CI. TODO: Remove.

for include in "$(dirname $0)/../include/"*; do source "$include"; done

export MIXBOX_CI_BUILD_EXECUTABLE="CheckDemoTask"
"$MIXBOX_CI_SCRIPT_DIRECTORY"/../swift/run_swift