#!/bin/bash

MIXBOX_CI_TEMPORARY_DIRECTORY="/tmp/EAF744B8-3A57-473C-95E9-B1A7B7FA1BDD"
for include in "$(dirname $0)/../include/"*; do source "$include"; done

xcodebuildFilter() {
    xcpretty -r junit -o "$MIXBOX_CI_REPORTS_PATH/junit.xml"
}

prepareForTesting
buildWith_action_scheme_xcodebuildPipeFilter "test" "UnitTests" "xcodebuildFilter"
cleanUpAfterTesting