#!/bin/bash

# Required environment:
# MIXBOX_CI_REPORTS_PATH - where to store reports (junit.xml will be stored), e.g. "/tmp/123"
# MIXBOX_CI_DESTINATION - basename of json in `di/destinations` directory, e.g. "iphone_7_ios114.json"

MIXBOX_CI_TEMPORARY_DIRECTORY="/tmp/EAF744B8-3A57-473C-95E9-B1A7B7FA1BDD"
for include in "$(dirname $0)/../include/"*; do source "$include"; done

xcodebuildFilter() {
    xcpretty -r junit -o "$MIXBOX_CI_REPORTS_PATH/junit.xml"
}

prepareForTesting
buildWith_action_scheme_xcodebuildPipeFilter "test" "UnitTests" "xcodebuildFilter"
cleanUpAfterTesting