#!/bin/bash

set -x

MIXBOX_CI_SCRIPT_DIRECTORY=$(cd "$(dirname $0)"; pwd)
MIXBOX_CI_REPO_ROOT=$(cd "$MIXBOX_CI_SCRIPT_DIRECTORY"; git rev-parse --show-toplevel)

[ -z "$MIXBOX_PUSHSPEC_STYLE" ] && echo "MIXBOX_PUSHSPEC_STYLE is not set (e.g. debug)" && exit 1
[ -z "$MIXBOX_PUSHSPEC_VERSION" ] && echo "MIXBOX_PUSHSPEC_VERSION is not set (e.g. 0.0.1)" && exit 1
[ -z "$MIXBOX_PUSHSPEC_ORIGIN" ] && echo "MIXBOX_PUSHSPEC_ORIGIN is not set (e.g. origin)" && exit 1

# Optional:
#
# MIXBOX_PUSHSPEC_SKIP_UNTIL, e.g.: MixboxIpc.podspec

patch_spec_tmpfile=/tmp/`uuidgen`
function patchPodspecFile() {
    local podspecFile=$1
    cat "$podspecFile" | perl -pe "s/(s.version.*?= )'.*'/\1'$MIXBOX_PUSHSPEC_VERSION'/" > "$patch_spec_tmpfile"
    cat "$patch_spec_tmpfile" > "$podspecFile"
}

function pushSpec() {
    setLintingPodspecsEnabled false
    
    case "$MIXBOX_PUSHSPEC_STYLE" in
    debug)
        pod repo push MixboxSpecRepo "$@" --verbose --local-only --allow-warnings || exit 1
        ;;
    release)
        pod trunk push "$@" --verbose --allow-warnings || exit 1
        ;;
    *)
        setLintingPodspecsEnabled true
        echo "Unknown MIXBOX_PUSHSPEC_STYLE ($MIXBOX_PUSHSPEC_STYLE)"
        exit 1
        ;;
    esac
    
    setLintingPodspecsEnabled true
}

function setLintingPodspecsEnabled() {
    local enabled=$1
    local ruby="$(realpath "$(dirname "$(which pod)")/..")"
    local regex
    
    if [ "$enabled" == "true" ]
    then
        regex='s/#validate_podspec\(_files\)*/validate_podspec\1/g'
    elif [ "$enabled" == "false" ]
    then
        regex='s/  validate_podspec\(_files\)*/  #validate_podspec\1/g'
    else
        echo "Error in setLintingPodspecsEnabled $@"
        exit 1
    fi
    
    find "$ruby"/gems/cocoapods* -name push.rb|xargs sed -i '.backup_before_push_specs' "$regex"
}

IFS=$'\n'

sequence=()

sequence=("${sequence[@]}" MixboxFakeSettingsAppMain.podspec)
sequence=("${sequence[@]}" MixboxFoundation.podspec)

sequence=("${sequence[@]}" MixboxTestability.podspec)

sequence=("${sequence[@]}" MixboxUiKit.podspec)
sequence=("${sequence[@]}" MixboxTestsFoundation.podspec)
sequence=("${sequence[@]}" MixboxIpc.podspec)
sequence=("${sequence[@]}" MixboxIpcCommon.podspec)
sequence=("${sequence[@]}" MixboxUiTestsFoundation.podspec)
sequence=("${sequence[@]}" MixboxBuiltinIpc.podspec)
sequence=("${sequence[@]}" MixboxIpcSbtuiClient.podspec)

sequence=("${sequence[@]}" MixboxIpcSbtuiHost.podspec)
sequence=("${sequence[@]}" MixboxInAppServices.podspec)
sequence=("${sequence[@]}" MixboxGray.podspec)
sequence=("${sequence[@]}" MixboxBlack.podspec)

actualFilesFile=/tmp/`uuidgen`
expectedFilesFile=/tmp/`uuidgen`

find "$MIXBOX_CI_REPO_ROOT" -depth 1 -name "*.podspec" | perl -pe "s#$MIXBOX_CI_REPO_ROOT/##" | sort > "$actualFilesFile"
echo "${sequence[@]}" | tr ' ' $'\n' | sort > "$expectedFilesFile"

if ! diff "$actualFilesFile" "$expectedFilesFile"
then
    echo "^ - Error: you must have ordered podspec list, starting with podspecs with least dependencies"
    echo "           or algorithm that will do it automatically. The lines above is diff between expected podspecs and actual."
    exit 1
fi

tag="Mixbox-$MIXBOX_PUSHSPEC_VERSION"

git tag -d "$tag"
git tag "$tag"
git push --force "$MIXBOX_PUSHSPEC_ORIGIN" "$tag"

shouldSkip=true

for podspecFile in "${sequence[@]}"
do
    if ! [ -z "$MIXBOX_PUSHSPEC_SKIP_UNTIL" ]
    then
        [ "$MIXBOX_PUSHSPEC_SKIP_UNTIL.podspec" == "$podspecFile" ] && shouldSkip=false
        
        if "$shouldSkip"
        then
            continue
        fi
    fi
    
    # It is complicated. It requires MixboxInAppServices, but all of its code is under `#if` macro
    # and thus doesn't exist during linting of podspec.
    # There will be a lot  of other problems. SBTUITestTunnel can not be configured this way (without forking). If some
    # framework includes its header it uses its own preprocessor definitions and Swift flags.
    # There is also some caching problems when lintng specs. It stopped me to release MixboxGray after few hours.
    # However, gray box testing was also incomplete.
    
    if [ "$podspecFile" == "MixboxGray.podspec" ]
    then
        continue
    fi
    
    echo "$podspecFile"
    
    patchPodspecFile "$MIXBOX_CI_REPO_ROOT/$podspecFile"
    pushSpec "$MIXBOX_CI_REPO_ROOT/$podspecFile"
done
