#!/bin/bash

# Required environment:
# MIXBOX_CI_REPORTS_PATH - where to store reports (junit.xml will be stored), e.g. "/tmp/123"
# MIXBOX_CI_DESTINATION - basename of json in `di/destinations` directory, e.g. "iphone_7_ios114.json"

for include in "$(dirname $0)/../include/"*; do source "$include"; done

prepareForIosTesting
installEmceeWithDependencies
buildIosWith_folder_action_scheme_workspace_xcodebuildPipeFilter "Tests" "build-for-testing" "BlackBoxUiTests" "Tests" "xcpretty"
testUsingEmceeWith_appName_testsTarget_additionalApp "TestedApp.app" "BlackBoxUiTests" "FakeSettingsApp.app"
generateReports
cleanUpAfterIosTesting
