#!/bin/bash

# Required environment:
# MIXBOX_CI_REPORTS_PATH - where to store reports (junit.xml will be stored), e.g. "/tmp/123"
# MIXBOX_CI_DESTINATION - basename of json in `di/destinations` directory, e.g. "iphone_7_ios114.json"

MIXBOX_CI_TEMPORARY_DIRECTORY="/tmp/083D9EF7-033B-43C3-8D35-2273367B6F92"
for include in "$(dirname $0)/../include/"*; do source "$include"; done

installAdditionalDependencies() {
    installBluepill
}

installBluepill() {
    [ -z "$MIXBOX_CI_BLUEPILL_ZIP_PATH" ] && fatalError "MIXBOX_CI_BLUEPILL_ZIP_PATH is not set"
    
    curl -L "$MIXBOX_CI_BLUEPILL_ZIP_PATH" | tar xz --strip=1 --directory "$MIXBOX_CI_TEMPORARY_DIRECTORY"
}

bluepill() {
    "$MIXBOX_CI_TEMPORARY_DIRECTORY/bluepill" "$@"
}

testUsingBluepill() {
    echo "Running tests"

    cd "$MIXBOX_CI_SCRIPT_DIRECTORY"
    
    local reuseSimulatorOption=""
    if ! bluepill --version | grep "v3" > /dev/null
    then
        reuseSimulatorOption="--reuse-simulator"
    fi
    
    bluepill \
    "$reuseSimulatorOption" \
    --headless \
    --device "$(destination | jq -r .[0].testDestination.deviceType)" \
    --runtime "iOS $(destination | jq -r .[0].testDestination.iOSVersionShort)" \
    --xctestrun-path "$(ls -1 "$(derivedDataPath)"/Build/Products/XcuiTests_iphonesimulator*.xctestrun|head -1)" \
    --error-retries 1 \
    --failure-tolerance 1 \
    --stuck-timeout 600 \
    --test-timeout 1200 \
    --num-sims 4 \
    --junit-output \
    -o "$MIXBOX_CI_REPORTS_PATH/junit.xml"
}


prepareForTesting
installAdditionalDependencies
buildWith_action_scheme_xcodebuildPipeFilter "build-for-testing" "XcuiTests" "xcpretty"
testUsingBluepill
cleanUpAfterTesting
