#!/bin/bash

# Required environment:
# MIXBOX_CI_REPORTS_PATH - where to store reports (junit.xml will be stored), e.g. "/tmp/123"
# MIXBOX_CI_DESTINATION - basename of json in `di/destinations` directory, e.g. "iphone_7_ios114.json"

MIXBOX_CI_TEMPORARY_DIRECTORY="/tmp/083D9EF7-033B-43C3-8D35-2273367B6F92"
for include in "$(dirname $0)/../include/"*; do source "$include"; done

installAdditionalDependencies() {
    which bluepill || brew install bluepill
}

testUsingBluepill() {
    echo "Running tests"

    cd "$MIXBOX_CI_SCRIPT_DIRECTORY"
    
    bluepill \
    --reuse-simulator \
    --headless \
    --xctestrun-path "$(ls -1 "$(derivedDataPath)"/Build/Products/XcuiTests_iphonesimulator*.xctestrun|head -1)" \
    --num-sims 4 \
    --junit-output \
    -o "$MIXBOX_CI_REPORTS_PATH/junit.xml"
}


prepareForTesting
installAdditionalDependencies
buildWith_action_scheme "build-for-testing" "XcuiTests"
testUsingBluepill
cleanUpAfterTesting
