#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 120400 && __IPHONE_OS_VERSION_MAX_ALLOWED < 130000

#import "Xcode_10_3_XCTest_CDStructures.h"
#import "Xcode_10_3_SharedHeader.h"
#import <Foundation/Foundation.h>

@class XCTDarwinNotificationExpectation;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface _XCTDarwinNotificationExpectationImplementation : NSObject
{
    XCTDarwinNotificationExpectation *_expectation;
    NSString *_notificationName;
    int _notifyToken;
    CDUnknownBlockType _handler;
    NSObject *_queue;
    _Bool _hasCleanedUp;
}

@property(readonly, copy) NSString *notificationName; // @synthesize notificationName=_notificationName;
- (void)cleanup;
- (void)_handleNotification;
@property(copy) CDUnknownBlockType handler;
- (id)initWithNotificationName:(id)arg1 expectation:(id)arg2;
- (void)dealloc;

@end

#endif