#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCUIAutomation_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import "Xcode_15_0_XCUIScreenDataSource.h"
#import <Foundation/Foundation.h>

@protocol XCUILocalDeviceScreenRecordingIPCInterface, XCUILocalDeviceScreenshotIPCInterface;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCUILocalDeviceScreenDataSource : NSObject <XCUIScreenDataSource>
{
    id <XCUILocalDeviceScreenshotIPCInterface> _screenshotIPCInterface;
    id <XCUILocalDeviceScreenRecordingIPCInterface> _screenRecordingIPCInterface;
}

@property(retain, nonatomic) id <XCUILocalDeviceScreenRecordingIPCInterface> screenRecordingIPCInterface; // @synthesize screenRecordingIPCInterface=_screenRecordingIPCInterface;
@property(retain, nonatomic) id <XCUILocalDeviceScreenshotIPCInterface> screenshotIPCInterface; // @synthesize screenshotIPCInterface=_screenshotIPCInterface;
@property(readonly, nonatomic) _Bool supportsScreenRecording;
@property(readonly, nonatomic) _Bool preferScreenshotsOverScreenRecordings;
- (void)stopScreenRecordingWithUUID:(id)arg1 withReply:(CDUnknownBlockType)arg2;
- (void)startScreenRecordingWithRequest:(id)arg1 withReply:(CDUnknownBlockType)arg2;
- (id)_clippedScreenshotFromImage:(id)arg1 encoding:(id)arg2 rect:(struct CGRect)arg3;
- (void)requestScreenshotAttachmentWithRequest:(id)arg1 withReply:(CDUnknownBlockType)arg2;
- (void)requestScreenshotWithRequest:(id)arg1 withReply:(CDUnknownBlockType)arg2;
- (void)requestBoundsForScreenWithIdentifier:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestScaleForScreenWithIdentifier:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestTraitsForScreenWithIdentifier:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_displayWithIdentifier:(long long)arg1;
- (void)requestScreenIdentifiersWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) _Bool supportsHEICImageEncoding;
- (id)initWithScreenshotIPCInterface:(id)arg1 screenRecordingIPCInterface:(id)arg2;

// Remaining properties

@end

#endif