#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCUIAutomation_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCUIAccessibilityAction : NSObject
{
    int _actionNumber;
}

+ (id)decrementActionForPlatform:(long long)arg1;
+ (id)incrementActionForPlatform:(long long)arg1;
+ (id)scrollToVisibleAction;
+ (id)detectAnimationsNonActiveAction;
+ (id)beginMonitoringIdleRunLoopAction;
@property(readonly) int actionNumber; // @synthesize actionNumber=_actionNumber;
- (id)description;
- (id)initWithAXAction:(int)arg1;

@end

#endif