#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCUIAutomation_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import "Xcode_15_0_XCActivityRecord.h"

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCActivityRecord (UITesting)
+ (id)createSnapshotAsTextAttachment:(id)arg1 withBundleID:(id)arg2;
+ (id)createSnapshotAttachment:(id)arg1;
- (void)attachDiagnosticScreenRecordingForScreen:(id)arg1;
- (void)attachDiagnosticScreenRecordingForDevice:(id)arg1;
- (void)attachDiagnosticScreenshotForScreen:(id)arg1;
- (void)attachDiagnosticScreenshotForDevice:(id)arg1;
- (void)addLocalizableStringsData:(id)arg1;
- (void)addSynthesizedEvent:(id)arg1 withScreen:(id)arg2;
- (void)addSnapshotAsText:(id)arg1 withBundleID:(id)arg2;
- (void)addSnapshot:(id)arg1;
- (void)addScreenImageData:(id)arg1 forceKeepAlways:(_Bool)arg2;
@end

#endif