#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCUIAutomation_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import "Xcode_15_0_XCTRunnerIDESession.h"
#import "Xcode_15_0_XCTRunnerIDESessionUIAutomationDelegate.h"
#import "Xcode_15_0_XCUIXcodeApplicationManaging.h"

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTRunnerIDESession (UIAutomation) <XCUIXcodeApplicationManaging, XCTRunnerIDESessionUIAutomationDelegate>
- (void)requestDiagnosticsForAdditionalDevices:(id)arg1;
- (void)processWithToken:(id)arg1 exitedWithStatus:(id)arg2;
- (void)stopTrackingProcessWithToken:(id)arg1;
- (void)processWithBundleID:(id)arg1 path:(id)arg2 pid:(id)arg3 crashedUnderSymbol:(id)arg4;
- (void)terminateProcessWithToken:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestLaunchProgressForProcessWithToken:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)openURL:(id)arg1 processPath:(id)arg2 bundleID:(id)arg3 arguments:(id)arg4 environmentVariables:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)launchProcessWithPath:(id)arg1 bundleID:(id)arg2 arguments:(id)arg3 environmentVariables:(id)arg4 completion:(CDUnknownBlockType)arg5;

// Remaining properties
@end

#endif