#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCUIAutomation_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import "Xcode_15_0_XCUIElementBaseEventTarget.h"
#import "Xcode_15_0_XCUIElementEventTarget.h"

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCUIElementEmbeddedEventTarget : XCUIElementBaseEventTarget <XCUIElementEventTarget>
{
}

- (_Bool)_swipe:(unsigned long long)arg1 withVelocity:(double)arg2 error:(id *)arg3;
- (_Bool)clickForDuration:(double)arg1 thenDragToElement:(id)arg2 withVelocity:(double)arg3 thenHoldForDuration:(double)arg4 error:(id *)arg5;
- (_Bool)rightClickWithError:(id *)arg1;
- (_Bool)doubleClickWithError:(id *)arg1;
- (_Bool)clickWithError:(id *)arg1;
- (_Bool)hoverWithError:(id *)arg1;
- (_Bool)swipeDownWithVelocity:(double)arg1 error:(id *)arg2;
- (_Bool)swipeDownWithError:(id *)arg1;
- (_Bool)swipeUpWithVelocity:(double)arg1 error:(id *)arg2;
- (_Bool)swipeUpWithError:(id *)arg1;
- (_Bool)swipeRightWithVelocity:(double)arg1 error:(id *)arg2;
- (_Bool)swipeRightWithError:(id *)arg1;
- (_Bool)swipeLeftWithVelocity:(double)arg1 error:(id *)arg2;
- (_Bool)swipeLeftWithError:(id *)arg1;
- (_Bool)tapWithNumberOfTaps:(unsigned long long)arg1 numberOfTouches:(unsigned long long)arg2 error:(id *)arg3;
- (_Bool)twoFingerTapWithError:(id *)arg1;
- (_Bool)doubleTapWithError:(id *)arg1;
- (_Bool)tapWithError:(id *)arg1;

// Remaining properties

@end

#endif