#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 140000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 150000

#import "Xcode_12_0_XCTest_CDStructures.h"
#import "Xcode_12_0_SharedHeader.h"
#import <XCTest/XCTKVOExpectation.h>
#import <XCTest/XCTestExpectation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTKVOExpectation ()
{
    _Bool _hasCleanedUp;
    CDUnknownBlockType _handler;
    NSString *_keyPath;
    id _observedObject;
    id _expectedValue;
    unsigned long long _options;
    NSObject *_queue;
}

@property _Bool hasCleanedUp; // @synthesize hasCleanedUp=_hasCleanedUp;
@property(readonly) NSObject *queue; // @synthesize queue=_queue;
- (void)cleanup;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

- (void)dealloc;

@end

#endif