#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 140000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 150000

#import "Xcode_12_0_XCTest_CDStructures.h"
#import "Xcode_12_0_SharedHeader.h"
#import <Foundation/Foundation.h>
#import <XCTest/XCTestRun.h>

@class XCTIssue, XCTest, XCTestObservationCenter;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTestRun ()
{
    _Bool _hasBeenSkipped;
    _Bool _hasStarted;
    _Bool _hasStopped;
    XCTest *_test;
    unsigned long long _executionCount;
    unsigned long long _failureCount;
    unsigned long long _unexpectedExceptionCount;
    double _startTimeInterval;
    double _stopTimeInterval;
    XCTIssue *_candidateIssue;
    unsigned long long _executionCountBeforeCrash;
    unsigned long long _skipCountBeforeCrash;
    unsigned long long _failureCountBeforeCrash;
    unsigned long long _unexpectedExceptionCountBeforeCrash;
}

@property unsigned long long unexpectedExceptionCountBeforeCrash; // @synthesize unexpectedExceptionCountBeforeCrash=_unexpectedExceptionCountBeforeCrash;
@property unsigned long long failureCountBeforeCrash; // @synthesize failureCountBeforeCrash=_failureCountBeforeCrash;
@property unsigned long long skipCountBeforeCrash; // @synthesize skipCountBeforeCrash=_skipCountBeforeCrash;
@property unsigned long long executionCountBeforeCrash; // @synthesize executionCountBeforeCrash=_executionCountBeforeCrash;
@property(retain) XCTIssue *candidateIssue; // @synthesize candidateIssue=_candidateIssue;
@property _Bool hasStopped; // @synthesize hasStopped=_hasStopped;
@property _Bool hasStarted; // @synthesize hasStarted=_hasStarted;
@property double stopTimeInterval; // @synthesize stopTimeInterval=_stopTimeInterval;
@property double startTimeInterval; // @synthesize startTimeInterval=_startTimeInterval;
- (void)_handleIssue:(id)arg1;
- (void)_recordIssue:(id)arg1;

- (void)recordSkipWithDescription:(id)arg1 inFile:(id)arg2 atLine:(unsigned long long)arg3;
- (void)stop;
- (void)start;
@property(readonly) XCTestObservationCenter *observationCenter;
- (id)description;

@end

#endif