#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 140000

#import "Xcode_11_0_XCTest_CDStructures.h"
#import "Xcode_11_0_MXMInstrumental.h"
#import "Xcode_11_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@protocol XCTMetric;

@class XCTPerformanceMeasurementTimestamp;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTMetricInstrumentalAdapter : NSObject <MXMInstrumental>
{
    XCTPerformanceMeasurementTimestamp *_startTimestamp;
    XCTPerformanceMeasurementTimestamp *_stopTimestamp;
    id <XCTMetric> _metric;
}

@property(retain, nonatomic) id <XCTMetric> metric; // @synthesize metric=_metric;
- (_Bool)harvestData:(id *)arg1 error:(id *)arg2;
- (void)didStopAtTime:(unsigned long long)arg1 stopDate:(id)arg2;
- (void)didStartAtTime:(unsigned long long)arg1 startDate:(id)arg2;
- (void)willStartAtEstimatedTime:(unsigned long long)arg1;
- (_Bool)prepareWithOptions:(id)arg1 error:(id *)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithMetric:(id)arg1;

@end

#endif