#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 140000

#import "Xcode_11_0_XCTest_CDStructures.h"
#import "Xcode_11_0_SharedHeader.h"
#import <XCTest/XCTest.h>

@class XCTestConfiguration;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface _XCTestSuiteImplementation : XCTest
{
    NSString *_name;
    NSMutableArray *_tests;
    XCTestConfiguration *_testConfiguration;
    NSMutableDictionary *_activityAggregateStatistics;
}

@property(readonly) NSMutableDictionary *activityAggregateStatistics; // @synthesize activityAggregateStatistics=_activityAggregateStatistics;
@property(retain) XCTestConfiguration *testConfiguration; // @synthesize testConfiguration=_testConfiguration;
@property(retain) NSMutableArray *tests; // @synthesize tests=_tests;
@property(copy) NSString *name; // @synthesize name=_name;
- (id)initWithName:(id)arg1;

@end

#endif