#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 140000

#import "Xcode_11_0_XCTest_CDStructures.h"
#import "Xcode_11_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@class XCTestExpectation;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTPromise : NSObject
{
    // Error parsing type: {atomic_flag="_Value"AB}, name: _promiseFulfilled
    NSString *_promiseDescription;
    id _value;
    NSError *_error;
    XCTestExpectation *_expectation;
}

// Error parsing type for property promiseFulfilled:
// Property attributes: T{atomic_flag=AB},R,V_promiseFulfilled

@property(readonly) XCTestExpectation *expectation; // @synthesize expectation=_expectation;
@property(retain) NSError *error; // @synthesize error=_error;
@property(retain) id value; // @synthesize value=_value;
@property(readonly, copy) NSString *promiseDescription; // @synthesize promiseDescription=_promiseDescription;
- (void)fulfillWithValue:(id)arg1 error:(id)arg2;
- (void)fulfillWithError:(id)arg1;
- (void)fulfillWithValue:(id)arg1;
- (id)initWithDescription:(id)arg1;

@end

#endif