#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 140000

#import "Xcode_11_0_XCTest_CDStructures.h"
#import "Xcode_11_0_SharedHeader.h"
#import "Xcode_11_0_XCTElementSnapshotAttributeDataSource.h"

@class XCTCapabilities, XCTElementQuery, XCTElementQueryResults;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTRunnerAutomationSession <XCTElementSnapshotAttributeDataSource>
@property(readonly) _Bool supportsAnimationsIdleNotifications;
@property(readonly) _Bool supportsMainRunLoopIdleNotifications;
@property(readonly) _Bool supportsFetchingAttributesForElement;
@property(readonly) XCTCapabilities *remoteInterfaceCapabilities;
- (void)notifyWhenAnimationsAreIdle:(void (^)(NSError *))arg1;
- (void)notifyWhenMainRunLoopIsIdle:(void (^)(NSError *))arg1;
- (XCTElementQueryResults *)matchesForQuery:(XCTElementQuery *)arg1 error:(id *)arg2;
@end

#endif
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 140000

#import "Xcode_11_0_XCTest_CDStructures.h"
#import "Xcode_11_0_SharedHeader.h"
#import "Xcode_11_0_XCTRunnerAutomationSession.h"
#import <Foundation/Foundation.h>

@class XCTCapabilities;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTRunnerAutomationSession : NSObject <XCTRunnerAutomationSession>
{
    int _connectionPid;
    NSXPCConnection *_connection;
    XCTCapabilities *_remoteInterfaceCapabilities;
}

+ (id)legacyCapabilitiesForOSVersion:(CDStruct_2ec95fd7)arg1 platform:(unsigned long long)arg2 error:(id *)arg3;
+ (id)exportedCapabilities;
+ (void)requestSessionWithEndpoint:(id)arg1 pid:(int)arg2 completion:(CDUnknownBlockType)arg3;
@property(retain) XCTCapabilities *remoteInterfaceCapabilities; // @synthesize remoteInterfaceCapabilities=_remoteInterfaceCapabilities;
@property(readonly) int connectionPid; // @synthesize connectionPid=_connectionPid;
@property(readonly) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(readonly) _Bool usePointTransformationsForFrameConversions;
@property(readonly) _Bool supportsHostedViewCoordinateTransformations;
- (id)parameterizedAttribute:(id)arg1 forElement:(id)arg2 parameter:(id)arg3 error:(id *)arg4;
- (id)attributesForElement:(id)arg1 attributes:(id)arg2 error:(id *)arg3;
@property(readonly) _Bool allowsRemoteAccess;
- (void)notifyWhenAnimationsAreIdle:(CDUnknownBlockType)arg1;
@property(readonly) _Bool supportsAnimationsIdleNotifications;
- (void)notifyWhenMainRunLoopIsIdle:(CDUnknownBlockType)arg1;
@property(readonly) _Bool supportsMainRunLoopIdleNotifications;
@property(readonly) _Bool supportsFetchingAttributesForElement;
- (id)matchesForQuery:(id)arg1 error:(id *)arg2;
- (id)initWithConnection:(id)arg1 pid:(int)arg2 remoteInterfaceCapabilities:(id)arg3;

// Remaining properties

@end

#endif