#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 140000

#import "Xcode_11_0_XCTest_CDStructures.h"
#import "Xcode_11_0_SharedHeader.h"
#import <Foundation/Foundation.h>
#import <XCTest/XCTMeasureOptions.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTMeasureOptions ()
{
    NSMutableDictionary *_instrumentOptions;
    _Bool _discardFirstIteration;
    unsigned long long _instrumentAutomatic;
    unsigned long long _metricPerferredSampleMode;
}

@property(nonatomic) _Bool discardFirstIteration; // @synthesize discardFirstIteration=_discardFirstIteration;
@property(readonly, nonatomic) unsigned long long metricPerferredSampleMode; // @synthesize metricPerferredSampleMode=_metricPerferredSampleMode;
@property(readonly, nonatomic) unsigned long long instrumentAutomatic; // @synthesize instrumentAutomatic=_instrumentAutomatic;
- (id)init;
- (id)initWithInstrumentOptionsDictionary:(id)arg1;
@property(nonatomic) _Bool allowContinuousSampling;
@property(nonatomic) _Bool allowConcurrentIterations;
@property(readonly, nonatomic) NSDictionary *instrumentOptions;

@end

#endif