#!/bin/bash

cd "$(dirname "$0")"

generatePackage() {
    ./MakePackage/make_package || exit 1
}

generateProject() {
    generatePackage
    swift package generate-xcodeproj --xcconfig-overrides Package.xcconfig --enable-code-coverage
}

clean() {
    swift package clean
    swift package reset
    rm -rf .build/
    rm *.xcodeproj
}

case "$1" in
    generate)
        generateProject
        ;;
    reopen)
        xcodeAppName=`xcode-select -p|grep -oE "([^/]+.app)"|sed 's/\.app//'`
        xcodeprojRelative=`ls -1|grep ".xcodeproj"`
        xcodeprojAbsolute=$(pwd)/$xcodeprojRelative
    	osascript -e '
            tell application "'$xcodeAppName'"
               tell workspace document "'$xcodeprojRelative'"
                   close saving yes
               end tell
            end tell'
        
        if ! generateProject
        then
            open Package.swift
            exit 1
        fi
        
        echo "Ignore the following \"missing value\" log:"
    	osascript -e '
            tell application "'$xcodeAppName'"
               open "'$xcodeprojAbsolute'"
            end tell'

        echo "Quote from Apple:"
        echo "> KNOWN ISSUE: The open command in Xcode sometimes fails to return the opened document."
        echo "> It is recommended to ignore the result of the open command and instead find the opened"
        echo "> document in the application's documents."
        
        ;;
    clean)
        clean
        ;;
    build)
        clean
        swift build -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.13" --static-swift-stdlib
        ;;
    test)
        clean
        swift test -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.13"
        ;;
esac