#!/bin/bash

set -xueo pipefail

# ====== bash_ci ======
# This section should be same across all bash files in the project
source "$(builtin cd "$(dirname "$0")" && git rev-parse --show-toplevel)/ci/bash/bash_ci.sh"
# =====================

# The only job of this script is to
# run swift code with proper dependencies, including proper version of swift

main() {
    print_status
    print_instructions_to_reproduce_this_build
    build
    execute
}

print_status() {
    echo "##teamcity[progressMessage '$MIXBOX_CI_BUILD_EXECUTABLE']"
}

print_instructions_to_reproduce_this_build() {
    echo "Reproduce this build:"
    echo
    echo "$(print_mixbox_ci_environments) MIXBOX_CI_REPORTS_PATH=/tmp $0"
    echo
}

print_mixbox_ci_environments() {
    env \
        | grep -E "^(MIXBOX_|EMCEE_)" \
        | grep -v MIXBOX_CI_REPORTS_PATH \
        | tr "\n" " " \
        | sed 's/\*\*\*\*\*\*\*/some_password_hidden_by_ci/'
}

build() {
    cd "$SCRIPT_ROOT"
    
    local lastExitCode=0
    local maxAttempts=3
    for attempt in $(seq 1 $maxAttempts)
    do
        # Workaround for this:
        #   Failed to connect to github.com port 443: Operation timed out
        # Also this:
        #   /xxx/yyy/DeveloperDirLocator.swift:2:8: error: no such module 'Models'
        # The latter is maybe due to some SPM cache problems that can be solved (TODO: solve)
        if build_once "$attempt"; then
            echo "Build was successful"
            lastExitCode=0
            break
        else
            lastExitCode=$?
            echo "Failed to build, attempt #$attempt/$maxAttempts"; sleep 10
        fi
    done

    cd -
    
    return $lastExitCode
}

build_once() {
    local attempt_number=$1

    body() {
        "$SCRIPT_ROOT/make.sh" build "$MIXBOX_CI_BUILD_EXECUTABLE"
    }

    { set +x; } 2>/dev/null && ci_log_block "Building... (attempt $attempt_number)" body ${@+"$@"}
}

execute() {
    "$SCRIPT_ROOT/make.sh" launch "$MIXBOX_CI_BUILD_EXECUTABLE"
}

main "$@"
