#!/bin/bash

set -xueo pipefail

SCRIPT_ROOT=$(cd "$(dirname "$0")"; pwd)
REPO_ROOT=$(cd "$SCRIPT_ROOT"; cd "$(git rev-parse --show-toplevel)"; pwd)

# The only job of this script is to
# run swift code with proper dependencies, including proper version of swift

main() {
    print_status
    print_instructions_to_reproduce_this_build
    check_dependencies
    build
    execute
}

print_status() {
    echo "##teamcity[progressMessage '$MIXBOX_CI_BUILD_EXECUTABLE']"
}

print_instructions_to_reproduce_this_build() {
    echo "Reproduce this build:"
    echo
    echo "$(print_mixbox_ci_environments) MIXBOX_CI_REPORTS_PATH=/tmp $0"
    echo
}

print_mixbox_ci_environments() {
    env \
        | grep -E "^(MIXBOX_|EMCEE_)" \
        | grep -v MIXBOX_CI_REPORTS_PATH \
        | tr "\n" " " \
        | sed 's/\*\*\*\*\*\*\*/some_password_hidden_by_ci/'
}

check_dependencies() {
    install_command_line_tools_if_needed
}

install_command_line_tools_if_needed() {
    pkgutil --pkg-info=com.apple.pkg.CLTools_Executables || install_command_line_tools
}

install_command_line_tools() {
    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress

    local savedIFS=$IFS
    IFS=$'\n'
    for packageName in $(softwareupdate -l|grep "\*.*Command Line"|awk -F"*" '{print $2}'|sed -e 's/^ *//')
    do
        softwareupdate -i "$packageName"
    done
    IFS=$savedIFS
}

build() {
    cd "$SCRIPT_ROOT"
    
    lastExitCode=0
    maxAttempts=3
    for attempt in `seq 1 $maxAttempts`
    do
        # Workaround for this:
        #   Failed to connect to github.com port 443: Operation timed out
        # Also this:
        #   /xxx/yyy/DeveloperDirLocator.swift:2:8: error: no such module 'Models'
        # The latter is maybe due to some SPM cache problems that can be solved (TODO: solve)
        if "$SCRIPT_ROOT/make.sh" build "$MIXBOX_CI_BUILD_EXECUTABLE"; then
            echo "Build was successful"
            lastExitCode=0
            break
        else
            lastExitCode=$?
            echo "Failed to build, attempt #$attempt/$maxAttempts"; sleep 10
        fi
    done

    cd -
    
    return $lastExitCode
}

execute() {
    "$SCRIPT_ROOT/make.sh" launch "$MIXBOX_CI_BUILD_EXECUTABLE"
}

main "$@"
