#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTAutomationSupport_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@class CGImage, UIImage, XCTImageEncoding, XCTImageMetadata;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTImage : NSObject <NSCopying, NSSecureCoding>
{
    UIImage *_platformImage;
    XCTImageMetadata *_metadata;
    NSData *_data;
    XCTImageEncoding *_encoding;
}

+ (_Bool)supportsSecureCoding;
+ (id)emptyImageWithSize:(struct CGSize)arg1;
@property(readonly, copy, nonatomic) XCTImageEncoding *encoding; // @synthesize encoding=_encoding;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
@property(readonly, nonatomic) XCTImageMetadata *metadata; // @synthesize metadata=_metadata;
@property(retain, nonatomic) UIImage *platformImage; // @synthesize platformImage=_platformImage;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)debugQuickLookObject;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCGImage:(struct CGImage *)arg1 metadata:(id)arg2 orientation:(unsigned int)arg3;
- (id)initWithData:(id)arg1 encodedIn:(id)arg2 metadata:(id)arg3;
- (id)initWithImage:(id)arg1;

@end

#endif