#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTAutomationSupport_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"

@class XCUIPoint, XCUIRect;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCUIElementSnapshotCoordinateTransforms
- (XCUIPoint *)point:(struct CGPoint)arg1 transformedForEventSynthesisFromOrientation:(long long)arg2 error:(id *)arg3;
- (XCUIRect *)userOrientationTransformedEventSynthesisRect:(struct CGRect)arg1 error:(id *)arg2;
- (XCUIRect *)hostingAndOrientationTransformedRect:(struct CGRect)arg1 error:(id *)arg2;
- (XCUIPoint *)hostingAndOrientationTransformedPoint:(struct CGPoint)arg1 error:(id *)arg2;
@end

#endif
