#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTAutomationSupport_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@class XCTVideoEncoding;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTScreenRecordingRequest : NSObject <NSSecureCoding>
{
    long long _screenID;
    XCTVideoEncoding *_preferredEncoding;
    struct CGRect _rect;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) XCTVideoEncoding *preferredEncoding; // @synthesize preferredEncoding=_preferredEncoding;
@property(readonly, nonatomic) struct CGRect rect; // @synthesize rect=_rect;
@property(readonly, nonatomic) long long screenID; // @synthesize screenID=_screenID;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)initWithScreenID:(long long)arg1 rect:(struct CGRect)arg2 preferredEncoding:(id)arg3;

@end

#endif