#!/bin/bash

set -ueo pipefail

script_root=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "${script_root}/../../.." && pwd)

source "$REPO_ROOT/Tests/Scripts/mock_generation.sh"

# DSL

apply_mocks() {
    module "MixboxTestsFoundation"
    mock "TestFailureRecorder"
    
    module "MixboxUiTestsFoundation"
    mock "StubRequestBuilder"
    mock "StubResponseBuilder"
    mock "ElementImageProvider"
    mock "SnapshotsDifferenceAttachmentGenerator"
    mock "SnapshotsComparatorFactory"
    mock "PageObjectDependenciesFactory"
    mock "InteractionSettingsDefaultsProvider"
    
    module "UnitTests"
    mock "MocksTestsFixtureProtocol"
    mock "MocksTestsFixtureObjcProtocol"
    mock "MocksTestsFixtureBaseProtocolFromOtherFile"
    mock "MocksTestsFixtureSimpleProtocol"
    mock "DynamicBehaviorIntegrationalTestsProtocol"
    mock "EasyClosureStubbingIntegrationalTestsProtocol"

    module "MixboxMocksRuntime"
    mock "DynamicCallable"
    mock "DynamicCallableFactory"
    mock "MockManagerVerification"
    mock "MockManagerStubbing"
    mock "MockManagerStateTransferring"
    mock "MockManagerCalling"
    mock "StubsProvider"
    mock "RecordedCallsHolder"
        
    module "MixboxGenerators"
    mock "AnyGenerator"
}

generate "UnitTests" "${REPO_ROOT}/Tests/UnitTests/Mocks"
