#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 160000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 170000

#import "Xcode_14_0_XCUIAutomation_CDStructures.h"
#import "Xcode_14_0_SharedHeader.h"
#import <XCTest/XCTMetric.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTMemoryMetric (UIAutomation_Private)
- (id)targetApplication;
- (void)setTargetApplication:(id)arg1;
- (void)copyWithZone_UIAutomation:(struct _NSZone *)arg1 copyIntoObject:(id)arg2;
- (void)didStopMeasuringAtTimestamp_UIAutomation:(id)arg1;
- (id)initWithApplication:(id)arg1;
@end

#endif