#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 120200 && __IPHONE_OS_VERSION_MAX_ALLOWED < 120400

#import "Xcode_10_2_XCTAutomationSupport_CDStructures.h"
#import "Xcode_10_2_SharedHeader.h"
#import <Foundation/Foundation.h>

@protocol XCTMatchingElementIterator;

@class XCElementSnapshot;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTElementSetTransformer <NSObject>
@property _Bool stopsOnFirstMatch;
@property(readonly) _Bool supportsAttributeKeyPathAnalysis;
@property(copy) NSString *transformationDescription;
@property(readonly) _Bool supportsRemoteEvaluation;
- (NSSet *)requiredKeyPathsOrError:(id *)arg1;
- (id <XCTMatchingElementIterator>)iteratorForInput:(XCElementSnapshot *)arg1;
- (NSOrderedSet *)transform:(NSOrderedSet *)arg1 relatedElements:(id *)arg2;
@end

#endif
