#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@class XCTExpectedFailureOptions, XCTSourceCodeContext;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTExpectedFailureContext : NSObject
{
    _Bool _hasMatchedIssues;
    XCTExpectedFailureOptions *_options;
    NSString *_failureReason;
    XCTSourceCodeContext *_sourceCodeContext;
    unsigned long long _threadId;
}

@property(readonly) unsigned long long threadId; // @synthesize threadId=_threadId;
@property _Bool hasMatchedIssues; // @synthesize hasMatchedIssues=_hasMatchedIssues;
@property(retain) XCTSourceCodeContext *sourceCodeContext; // @synthesize sourceCodeContext=_sourceCodeContext;
@property(readonly, copy) NSString *failureReason; // @synthesize failureReason=_failureReason;
@property(readonly, copy) XCTExpectedFailureOptions *options; // @synthesize options=_options;
- (_Bool)matchesIssue:(id)arg1;
- (id)initWithFailureReason:(id)arg1 options:(id)arg2;

@end

#endif