#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>
#import <XCTest/XCTestExpectation.h>

@protocol XCTestExpectationDelegate;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTestExpectation ()
{
    // Error parsing type: {atomic_flag="_Value"AB}, name: _hasCleanedUp
    NSLock *_cleanupHandlersLock;
    NSMutableArray *_cleanupHandlers;
    _Bool _fulfilled;
    _Bool _hasBeenWaitedOn;
    _Bool _inverted;
    _Bool _assertForOverFulfill;
    id <XCTestExpectationDelegate> _delegate;
    unsigned long long _fulfillmentToken;
    NSArray *_fulfillCallStackReturnAddresses;
    NSString *_expectationDescription;
    unsigned long long _expectedFulfillmentCount;
    unsigned long long _numberOfFulfillments;
    unsigned long long _creationToken;
    NSArray *_creationCallStackReturnAddresses;
}

+ (id)expectationWithDescription:(id)arg1;
+ (id)compoundOrExpectationWithSubexpectations:(id)arg1;
+ (id)compoundAndExpectationWithSubexpectations:(id)arg1;
@property(readonly, copy) NSArray *creationCallStackReturnAddresses; // @synthesize creationCallStackReturnAddresses=_creationCallStackReturnAddresses;
@property(readonly) unsigned long long creationToken; // @synthesize creationToken=_creationToken;
@property unsigned long long numberOfFulfillments; // @synthesize numberOfFulfillments=_numberOfFulfillments;
- (void)addCleanupHandler:(CDUnknownBlockType)arg1;
- (void)cleanup:(_Bool)arg1;
@property _Bool hasBeenWaitedOn; // @synthesize hasBeenWaitedOn=_hasBeenWaitedOn;
@property __weak id <XCTestExpectationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSArray *fulfillCallStackReturnAddresses; // @synthesize fulfillCallStackReturnAddresses=_fulfillCallStackReturnAddresses;
@property(readonly) _Bool fulfilled; // @synthesize fulfilled=_fulfilled;
@property _Bool hasInverseBehavior;
@property(nonatomic) unsigned long long fulfillmentCount;
@property(readonly) unsigned long long fulfillmentToken; // @synthesize fulfillmentToken=_fulfillmentToken;
- (void)fulfill;
- (id)_generateExpectationDescription;
- (id)description;
- (void)dealloc;

- (id)init;

@end

#endif