#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <XCTest/XCTNSPredicateExpectation.h>
#import <XCTest/XCTestExpectation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTNSPredicateExpectation ()
{
    _Bool _isEvaluating;
    _Bool _shouldEvaluate;
    CDUnknownBlockType _handler;
    NSString *_debugDescription;
    NSPredicate *_predicate;
    id _object;
    NSRunLoop *_timerRunLoop;
    NSTimer *_timer;
    double _pollingInterval;
}

+ (double)initialPollingInterval;
@property double pollingInterval; // @synthesize pollingInterval=_pollingInterval;
@property _Bool shouldEvaluate; // @synthesize shouldEvaluate=_shouldEvaluate;
@property _Bool isEvaluating; // @synthesize isEvaluating=_isEvaluating;
@property(retain) NSTimer *timer; // @synthesize timer=_timer;
@property(retain) NSRunLoop *timerRunLoop; // @synthesize timerRunLoop=_timerRunLoop;
@property(copy) NSString *debugDescription; // @synthesize debugDescription=_debugDescription;
- (void)cleanup:(_Bool)arg1;
- (void)fulfill;
- (_Bool)_shouldFulfillForObject:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)_considerFulfilling;
- (void)_scheduleTimer;
- (void)startPolling;
- (void)setHasBeenWaitedOn:(_Bool)arg1;

// Remaining properties

@end

#endif