#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <XCTest/XCTestRun.h>
#import <XCTest/XCTestSuiteRun.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTestSuiteRun ()
{
    NSMutableArray *_mutableTestRuns;
}

@property(readonly) NSMutableArray *mutableTestRuns; // @synthesize mutableTestRuns=_mutableTestRuns;
- (void)recordExpectedFailure:(id)arg1;
- (void)_handleIssue:(id)arg1;
- (double)testDuration;
- (unsigned long long)unexpectedExceptionCount;
- (unsigned long long)failureCount;
- (unsigned long long)expectedFailureCount;
- (unsigned long long)skipCount;
- (unsigned long long)executionCount;

- (void)stop;
- (void)start;
- (id)initWithTest:(id)arg1;

@end

#endif