#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import "Xcode_15_0_XCTMessagingRole_AttachmentFinalizing.h"
#import "Xcode_15_0_XCTMessagingRole_AttachmentsDeleting.h"
#import "Xcode_15_0_XCTMessagingRole_ControlSessionInitiation.h"
#import "Xcode_15_0_XCTMessagingRole_DiagnosticsCollection.h"
#import "Xcode_15_0_XCTMessagingRole_RunnerSessionInitiation.h"
#import "Xcode_15_0_XCTMessagingRole_UIRecordingControl.h"
#import "Xcode_15_0__XCTMessaging_VoidProtocol.h"

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTMessagingChannel_IDEToDaemon <XCTMessagingRole_RunnerSessionInitiation, XCTMessagingRole_ControlSessionInitiation, XCTMessagingRole_UIRecordingControl, XCTMessagingRole_DiagnosticsCollection, XCTMessagingRole_AttachmentsDeleting, XCTMessagingRole_AttachmentFinalizing, _XCTMessaging_VoidProtocol>

@optional
- (void)__dummy_method_to_work_around_68987191;
@end

#endif
