#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@class XCTTestIdentifier;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTTestIdentifier : NSObject <NSCopying, NSSecureCoding>
{
}

+ (_Bool)supportsSecureCoding;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)bundleIdentifier;
+ (id)identifierForClass:(Class)arg1;
+ (id)leafIdentifierWithComponents:(id)arg1;
+ (id)containerIdentifierWithComponents:(id)arg1;
+ (id)containerIdentifierWithComponent:(id)arg1;
- (Class)classForCoder;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly) unsigned long long options;
- (id)componentAtIndex:(unsigned long long)arg1;
@property(readonly) unsigned long long componentCount;
@property(readonly) NSArray *components;
- (id)initWithComponents:(id)arg1 options:(unsigned long long)arg2;
- (id)initWithStringRepresentation:(id)arg1 preserveModulePrefix:(_Bool)arg2;
- (id)initWithStringRepresentation:(id)arg1;
- (id)initWithClassName:(id)arg1;
- (id)initWithClassName:(id)arg1 methodName:(id)arg2;
- (id)initWithClassAndMethodComponents:(id)arg1;
- (id)initWithComponents:(id)arg1 isContainer:(_Bool)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly) XCTTestIdentifier *legacyEncodingCounterpart;
- (id)childIdentifierWithComponent:(id)arg1 isContainer:(_Bool)arg2;
@property(readonly) XCTTestIdentifier *objcMethodCounterpart;
@property(readonly) XCTTestIdentifier *swiftMethodCounterpart;
@property(readonly) XCTTestIdentifier *firstComponentIdentifier;
@property(readonly) XCTTestIdentifier *parentIdentifier;
- (id)_identifierString;
@property(readonly) NSString *legacyClassAndMethodStringRepresentation;
@property(readonly) NSString *identifierString;
@property(readonly) NSString *displayName;
@property(readonly) NSString *lastComponentDisplayName;
@property(readonly) NSString *lastComponent;
@property(readonly) NSString *firstComponent;
@property(readonly) _Bool representsBundle;
@property(readonly) _Bool isLeaf;
@property(readonly) _Bool isContainer;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)debugDescription;
- (id)description;
@property(readonly) _Bool encodingShouldIncludeLegacyKeys;

@end

#endif