#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import "Xcode_15_0_XCTTestWorker.h"
#import <Foundation/Foundation.h>

@class XCTBlockingQueue;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

__attribute__((visibility("hidden")))
@interface XCTExecutionWorker : NSObject <XCTTestWorker>
{
    _Bool _result;
    XCTBlockingQueue *_workQueue;
    NSError *_error;
    NSArray *_executionExtensions;
}

- (void)shutdown;
- (void)executeTestIdentifiers:(id)arg1 skippingTestIdentifiers:(id)arg2 completionHandler:(CDUnknownBlockType)arg3 completionQueue:(id)arg4;
- (void)fetchParallelizableTestIdentifiersWithCompletion:(CDUnknownBlockType)arg1;
- (void)fetchAllTestIdentifiersWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)runWithError:(id *)arg1;
- (void)enqueueTestIdentifiersToRun:(id)arg1 testIdentifiersToSkip:(id)arg2;
- (id)initWithExecutionExtensions:(id)arg1;

// Remaining properties

@end

#endif