#ifdef MIXBOX_ENABLE_IN_APP_SERVICES

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@interface UIApplication ()

- (void)handleKeyHIDEvent:(struct __IOHIDEvent *)arg1;

@end

#endif
