#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 120000

#import "Xcode9_XCTest_CDStructures.h"
#import "Xcode9_SharedHeader.h"
#import "Xcode9_XCElementSnapshot.h"

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCElementSnapshot (Hitpoint)
- (id)hitPointForScrolling:(id *)arg1;
- (id)hitPoint:(id *)arg1;
- (struct CGRect)_transformRect:(struct CGRect)arg1 windowContextID:(id)arg2 windowDisplayID:(id)arg3;
- (struct CGRect)hostingAndOrientationTransformedRect:(struct CGRect)arg1;
- (struct CGPoint)hostingAndOrientationTransformedPoint:(struct CGPoint)arg1;
- (struct CGPoint)_transformPoint:(struct CGPoint)arg1 windowContextID:(id)arg2 windowDisplayID:(id)arg3;
- (id)hitTest:(struct CGPoint)arg1;
- (id)_snapshotForAccessibilityElement:(id)arg1 error:(id *)arg2;
@end

#endif