# TODO: Improve local debug of podspecs
if ENV['LOCAL_SPEC_REPO'] == "true" 
  source ENV['HOME'] + '/.cocoapods/repos/MixboxSpecRepo'
  source 'https://github.com/CocoaPods/Specs'
end

project 'MixboxDemo.xcodeproj'
workspace 'MixboxDemo.xcworkspace'

platform :ios, :deployment_target => '9.0'

inhibit_all_warnings!
use_frameworks!

### TARGETS

target 'MixboxDemo' do
  pod 'MixboxInAppServices'
end

target 'MixboxDemoUITests' do
  inherit! :search_paths

  pod 'MixboxXcuiDriver'
  pod 'MixboxIpcSbtuiClient'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-D', 'DEBUG', '-D', 'TEST', '-Onone']
      config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEBUG=1', 'TEST=1', 'ENABLE_UITUNNEL=1']
    end
  end
end
