#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTAutomationSupport_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTTailspinRequest : NSObject <NSSecureCoding>
{
    _Bool _collectOSLogs;
    _Bool _collectOSSignposts;
    _Bool _redactSensitiveInformation;
    int _processID;
    NSDate *_startDate;
    NSString *_reason;
    NSString *_fileName;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(readonly, copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(readonly, copy, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
@property(readonly, nonatomic) _Bool redactSensitiveInformation; // @synthesize redactSensitiveInformation=_redactSensitiveInformation;
@property(readonly, nonatomic) _Bool collectOSSignposts; // @synthesize collectOSSignposts=_collectOSSignposts;
@property(readonly, nonatomic) _Bool collectOSLogs; // @synthesize collectOSLogs=_collectOSLogs;
@property(readonly, nonatomic) int processID; // @synthesize processID=_processID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)init;
- (id)initWithProcessID:(int)arg1 collectOSLogs:(_Bool)arg2 collectOSSignposts:(_Bool)arg3 redactSensitiveInformation:(_Bool)arg4 startDate:(id)arg5 reason:(id)arg6 fileName:(id)arg7;

@end

#endif