#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTAutomationSupport_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTSignpostEvent : NSObject <NSCopying, NSSecureCoding>
{
    int _processID;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) int processID; // @synthesize processID=_processID;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSignpostEvent:(id)arg1;
- (id)initWithProcessID:(int)arg1;

@end

#endif