#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 160000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 170000

#import "Xcode_14_0_XCTestCore_CDStructures.h"
#import "Xcode_14_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@class XCTSourceCodeSymbolInfo;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTSymbolInfoProviding <NSObject>
- (XCTSourceCodeSymbolInfo *)symbolInfoForImageOffset:(unsigned long long)arg1 forImageWithPath:(NSString *)arg2 andArch:(NSString *)arg3 error:(id *)arg4;
- (XCTSourceCodeSymbolInfo *)symbolInfoForImageOffset:(unsigned long long)arg1 inImageWithUUID:(NSString *)arg2 error:(id *)arg3;
- (XCTSourceCodeSymbolInfo *)symbolInfoForAddressInCurrentProcess:(unsigned long long)arg1 error:(id *)arg2;
@end

#endif
