#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@protocol XCTIssueHandling;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTExpectedFailureContextManager : NSObject
{
    id <XCTIssueHandling> _issueHandler;
    NSMutableArray *_threadAgnosticContextStack;
    NSMutableDictionary *_contextStacksByThreadId;
}

@property(readonly) NSMutableDictionary *contextStacksByThreadId; // @synthesize contextStacksByThreadId=_contextStacksByThreadId;
@property(readonly) NSMutableArray *threadAgnosticContextStack; // @synthesize threadAgnosticContextStack=_threadAgnosticContextStack;
@property(readonly) __weak id <XCTIssueHandling> issueHandler; // @synthesize issueHandler=_issueHandler;
- (void)checkForExpectedFailureMatchingIssue:(id)arg1;
- (void)popExpectedFailureContext:(id)arg1;
- (void)pushExpectedFailureContext:(id)arg1;
@property(readonly) NSArray *immutableExpectedFailureContextStackForCurrentThread;
- (id)expectedFailureContextStackForCurrentThread;
- (id)expectedFailureContextStackForThreadWithId:(unsigned long long)arg1;
- (void)_cleanUpContext:(id)arg1;
- (void)invalidate;
- (id)initWithIssueHandler:(id)arg1;

@end

#endif