#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import "Xcode_15_0_XCTTelemetryLogging.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTDaemonTelemetryLogger : NSObject <XCTTelemetryLogging>
{
    _Bool _isUITest;
    CDUnknownBlockType _eventDataSink;
    NSString *_sessionUUID;
    NSString *_osVersion;
    NSString *_hardwareModel;
    NSString *_frameworkVariant;
    NSString *_frameworkVersion;
    NSMutableDictionary *_localEvents;
    NSObject *_submissionGroup;
}

- (void)flushWithCompletion:(CDUnknownBlockType)arg1;
- (void)logCompletionOfTestIdentifier:(id)arg1;
- (void)logAnalyticsForCompletionOfTestIdentifier:(id)arg1;
- (void)logUsageOfFunction:(id)arg1;
- (void)logUsageOfClass:(id)arg1 method:(id)arg2;
- (void)logEventWithName:(id)arg1;
- (id)initWithSessionUUID:(id)arg1 OSVersion:(id)arg2 hardwareModel:(id)arg3 frameworkVariant:(id)arg4 frameworkVersion:(id)arg5 isUITest:(_Bool)arg6 eventDataSink:(CDUnknownBlockType)arg7;
- (id)initWithEventDataSink:(CDUnknownBlockType)arg1;
- (id)initWithRunnerDaemonSession:(id)arg1;

// Remaining properties

@end

#endif