#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@class XCTSignpostInterval;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTSignpostListener <NSObject>
- (void)receivedSignpost:(XCTSignpostInterval *)arg1 withToken:(NSUUID *)arg2;
- (void)unregisterForSignpostsWithToken:(NSUUID *)arg1;
- (NSUUID *)registerForSignpostsFromSubsystem:(NSString *)arg1 category:(NSString *)arg2 intervalTimeout:(double)arg3 error:(id *)arg4 handler:(void (^)(XCTSignpostInterval *))arg5;
@end

#endif
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import "Xcode_15_0_XCTSignpostListener.h"
#import <Foundation/Foundation.h>

@protocol XCTRemoteSignpostListenerProxy;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTSignpostListener : NSObject <XCTSignpostListener>
{
    id <XCTRemoteSignpostListenerProxy> _remoteSignpostListenerProxy;
    NSMutableDictionary *_tokensToHandlers;
}

+ (id)localSignpostListener;
+ (double)registerSignpostListenerTimeout;
@property(readonly) NSMutableDictionary *tokensToHandlers; // @synthesize tokensToHandlers=_tokensToHandlers;
@property(readonly) id <XCTRemoteSignpostListenerProxy> remoteSignpostListenerProxy; // @synthesize remoteSignpostListenerProxy=_remoteSignpostListenerProxy;
- (void)unregisterForSignpostsWithToken:(id)arg1;
- (id)registerForSignpostsFromSubsystem:(id)arg1 category:(id)arg2 intervalTimeout:(double)arg3 error:(id *)arg4 handler:(CDUnknownBlockType)arg5;
- (void)receivedSignpost:(id)arg1 withToken:(id)arg2;
- (id)initWithRemoteSignpostListenerProxy:(id)arg1;

// Remaining properties

@end

#endif