#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import "Xcode_15_0_XCTTelemetryLogging.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTTelemetryLogger : NSObject <XCTTelemetryLogging>
{
    NSArray *_loggers;
}

+ (double)defaultFlushTimeout;
+ (id)defaultLoggersWithRunnerDaemonSession:(id)arg1;
+ (instancetype)sharedLoggerIfInitiated;
+ (void)setSharedLogger:(id)arg1;
+ (instancetype)sharedLogger;
+ (void)initialize;
@property(readonly, copy) NSArray *loggers; // @synthesize loggers=_loggers;
- (void)logCompletionOfTestIdentifier:(id)arg1;
- (void)flushWithCompletion:(CDUnknownBlockType)arg1;
- (void)logUsageOfFunction:(id)arg1;
- (void)logUsageOfClass:(id)arg1 method:(id)arg2;
- (void)logEventWithName:(id)arg1;
- (void)flushWithTimeout:(double)arg1;
- (id)initWithLoggers:(id)arg1;
- (id)initWithRunnerDaemonSession:(id)arg1;
- (id)init;

// Remaining properties

@end

#endif