#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTFailableInvocation : NSObject
{
}

+ (id)invokeInvocation:(id)arg1 lastObservedErrorIssue:(id *)arg2;
+ (id)invokeInvocation:(id)arg1 withTestMethodConvention:(long long)arg2 lastObservedErrorIssue:(id *)arg3;
+ (id)invokeAsynchronousBlock:(CDUnknownBlockType)arg1 lastObservedErrorIssue:(id *)arg2;
+ (id)invokeSynchronousBlock:(CDUnknownBlockType)arg1 lastObservedErrorIssue:(id *)arg2;

@end

#endif