#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"

@class XCTAttachmentFutureMetadata, XCTScreenRecordingRequest;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol XCTMessagingRole_ScreenRecording
- (void)_XCT_stopScreenRecordingWithUUID:(NSUUID *)arg1 withReply:(void (^)(NSError *))arg2;
- (void)_XCT_startScreenRecordingWithRequest:(XCTScreenRecordingRequest *)arg1 withReply:(void (^)(XCTAttachmentFutureMetadata *, NSError *))arg2;
@end

#endif
