#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTActivityRecordStack : NSObject
{
    NSMutableArray *_storage;
    NSMutableDictionary *_mutableAggregationRecords;
}

@property(readonly) NSMutableDictionary *mutableAggregationRecords; // @synthesize mutableAggregationRecords=_mutableAggregationRecords;
@property(readonly) NSMutableArray *storage; // @synthesize storage=_storage;
@property(readonly) NSDictionary *aggregationRecords;
- (id)topActivity;
- (long long)depth;
- (void)unwindRemainingActivitiesWithObservationCenter:(id)arg1 context:(id)arg2;
- (void)didFinishActivity:(id)arg1 observationCenter:(id)arg2 context:(id)arg3;
- (id)willStartActivityWithTitle:(id)arg1 type:(id)arg2 observationCenter:(id)arg3 context:(id)arg4;
- (id)init;

@end

#endif