#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTRuntimeIssueDetectionPolicy : NSObject <NSSecureCoding>
{
    _Bool _detectionEnabled;
    long long _severity;
}

+ (_Bool)supportsSecureCoding;
+ (id)stringFromSeverity:(long long)arg1;
+ (id)defaultRuntimeIssueDetectionPolicy;
@property(readonly) long long severity; // @synthesize severity=_severity;
@property(readonly, getter=isDetectionEnabled) _Bool detectionEnabled; // @synthesize detectionEnabled=_detectionEnabled;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (_Bool)isEqualToPolicy:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)initWithDetectionEnabled:(_Bool)arg1;
- (id)initWithDetectionEnabled:(_Bool)arg1 severity:(long long)arg2;

@end

#endif