#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

@class XCTAggregateSuiteRunStatistics, XCTCapabilities, XCTRepetitionPolicy, XCTRuntimeIssueDetectionPolicy, XCTScreenCapturePolicy, XCTTestIdentifierSet;

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTestConfiguration : NSObject <NSSecureCoding, NSCopying>
{
    _Bool _reportResultsToIDE;
    _Bool _testsDrivenByIDE;
    _Bool _disablePerformanceMetrics;
    _Bool _treatMissingBaselinesAsFailures;
    _Bool _reportActivities;
    _Bool _testsMustRunOnMainThread;
    _Bool _initializeForUITesting;
    _Bool _initializeForMultiDevice;
    _Bool _shouldExtractMultiDeviceRequirements;
    _Bool _gatherLocalizableStringsData;
    _Bool _emitOSLogs;
    _Bool _testTimeoutsEnabled;
    NSString *_testBundleRelativePath;
    NSURL *_testBundleURL;
    XCTTestIdentifierSet *_testsToRun;
    XCTTestIdentifierSet *_testsToSkip;
    NSUUID *_sessionIdentifier;
    NSURL *_baselineFileURL;
    NSString *_baselineFileRelativePath;
    NSString *_targetApplicationPath;
    NSString *_targetApplicationBundleID;
    NSDictionary *_testApplicationDependencies;
    NSSet *_bundleIDsForCrashReportEmphasis;
    NSDictionary *_testApplicationUserOverrides;
    NSString *_productModuleName;
    NSString *_multiDeviceRequirementsFilePath;
    NSNumber *_traceCollectionEnabled;
    NSDictionary *_performanceTestConfiguration;
    NSNumber *_enablePerformanceTestsDiagnostics;
    NSDictionary *_targetApplicationEnvironment;
    NSArray *_targetApplicationArguments;
    XCTAggregateSuiteRunStatistics *_aggregateStatisticsBeforeCrash;
    NSString *_automationFrameworkPath;
    long long _systemAttachmentLifetime;
    long long _userAttachmentLifetime;
    long long _preferredScreenCaptureFormat;
    long long _testExecutionOrdering;
    NSNumber *_randomExecutionOrderingSeed;
    XCTRepetitionPolicy *_repetitionPolicy;
    XCTRuntimeIssueDetectionPolicy *_runtimeIssueDetectionPolicy;
    NSNumber *_defaultTestExecutionTimeAllowance;
    NSNumber *_maximumTestExecutionTimeAllowance;
    CDUnknownBlockType _randomNumberGenerator;
    NSString *_basePathForTestBundleResolution;
    XCTCapabilities *_IDECapabilities;
    NSDictionary *_applicationBundleInfos;
    NSDictionary *_multiDevicePlatformVersionMap;
}

+ (id)defaultBasePathForTestBundleResolution;
+ (id)defaultBasePathForTestBundleResolutionForMainBundlePath:(id)arg1;
+ (id)activeTestConfiguration;
+ (void)setActiveTestConfiguration:(id)arg1;
+ (_Bool)supportsSecureCoding;
@property(copy) NSDictionary *multiDevicePlatformVersionMap; // @synthesize multiDevicePlatformVersionMap=_multiDevicePlatformVersionMap;
@property(copy) NSDictionary *applicationBundleInfos; // @synthesize applicationBundleInfos=_applicationBundleInfos;
@property(retain) XCTCapabilities *IDECapabilities; // @synthesize IDECapabilities=_IDECapabilities;
@property(copy, nonatomic) NSString *basePathForTestBundleResolution; // @synthesize basePathForTestBundleResolution=_basePathForTestBundleResolution;
@property(copy) CDUnknownBlockType randomNumberGenerator; // @synthesize randomNumberGenerator=_randomNumberGenerator;
@property(copy, nonatomic) NSNumber *maximumTestExecutionTimeAllowance; // @synthesize maximumTestExecutionTimeAllowance=_maximumTestExecutionTimeAllowance;
@property(copy, nonatomic) NSNumber *defaultTestExecutionTimeAllowance; // @synthesize defaultTestExecutionTimeAllowance=_defaultTestExecutionTimeAllowance;
@property _Bool testTimeoutsEnabled; // @synthesize testTimeoutsEnabled=_testTimeoutsEnabled;
@property(retain) XCTRuntimeIssueDetectionPolicy *runtimeIssueDetectionPolicy; // @synthesize runtimeIssueDetectionPolicy=_runtimeIssueDetectionPolicy;
@property(retain) XCTRepetitionPolicy *repetitionPolicy; // @synthesize repetitionPolicy=_repetitionPolicy;
@property(retain) NSNumber *randomExecutionOrderingSeed; // @synthesize randomExecutionOrderingSeed=_randomExecutionOrderingSeed;
@property long long testExecutionOrdering; // @synthesize testExecutionOrdering=_testExecutionOrdering;
@property(nonatomic) long long preferredScreenCaptureFormat; // @synthesize preferredScreenCaptureFormat=_preferredScreenCaptureFormat;
@property long long userAttachmentLifetime; // @synthesize userAttachmentLifetime=_userAttachmentLifetime;
@property long long systemAttachmentLifetime; // @synthesize systemAttachmentLifetime=_systemAttachmentLifetime;
@property _Bool emitOSLogs; // @synthesize emitOSLogs=_emitOSLogs;
@property(copy) NSString *automationFrameworkPath; // @synthesize automationFrameworkPath=_automationFrameworkPath;
@property(copy) XCTAggregateSuiteRunStatistics *aggregateStatisticsBeforeCrash; // @synthesize aggregateStatisticsBeforeCrash=_aggregateStatisticsBeforeCrash;
@property(copy) NSArray *targetApplicationArguments; // @synthesize targetApplicationArguments=_targetApplicationArguments;
@property(copy) NSDictionary *targetApplicationEnvironment; // @synthesize targetApplicationEnvironment=_targetApplicationEnvironment;
@property _Bool gatherLocalizableStringsData; // @synthesize gatherLocalizableStringsData=_gatherLocalizableStringsData;
@property(copy) NSNumber *enablePerformanceTestsDiagnostics; // @synthesize enablePerformanceTestsDiagnostics=_enablePerformanceTestsDiagnostics;
@property(copy) NSDictionary *performanceTestConfiguration; // @synthesize performanceTestConfiguration=_performanceTestConfiguration;
@property(copy) NSNumber *traceCollectionEnabled; // @synthesize traceCollectionEnabled=_traceCollectionEnabled;
@property(copy) NSString *multiDeviceRequirementsFilePath; // @synthesize multiDeviceRequirementsFilePath=_multiDeviceRequirementsFilePath;
@property _Bool shouldExtractMultiDeviceRequirements; // @synthesize shouldExtractMultiDeviceRequirements=_shouldExtractMultiDeviceRequirements;
@property _Bool initializeForMultiDevice; // @synthesize initializeForMultiDevice=_initializeForMultiDevice;
@property _Bool initializeForUITesting; // @synthesize initializeForUITesting=_initializeForUITesting;
@property _Bool testsMustRunOnMainThread; // @synthesize testsMustRunOnMainThread=_testsMustRunOnMainThread;
@property _Bool reportActivities; // @synthesize reportActivities=_reportActivities;
@property(copy) NSString *productModuleName; // @synthesize productModuleName=_productModuleName;
@property(copy) NSDictionary *testApplicationUserOverrides; // @synthesize testApplicationUserOverrides=_testApplicationUserOverrides;
@property(copy) NSSet *bundleIDsForCrashReportEmphasis; // @synthesize bundleIDsForCrashReportEmphasis=_bundleIDsForCrashReportEmphasis;
@property(copy) NSDictionary *testApplicationDependencies; // @synthesize testApplicationDependencies=_testApplicationDependencies;
@property(copy) NSString *targetApplicationBundleID; // @synthesize targetApplicationBundleID=_targetApplicationBundleID;
@property(copy) NSString *targetApplicationPath; // @synthesize targetApplicationPath=_targetApplicationPath;
@property _Bool treatMissingBaselinesAsFailures; // @synthesize treatMissingBaselinesAsFailures=_treatMissingBaselinesAsFailures;
@property _Bool disablePerformanceMetrics; // @synthesize disablePerformanceMetrics=_disablePerformanceMetrics;
@property _Bool testsDrivenByIDE; // @synthesize testsDrivenByIDE=_testsDrivenByIDE;
@property _Bool reportResultsToIDE; // @synthesize reportResultsToIDE=_reportResultsToIDE;
@property(copy) NSString *baselineFileRelativePath; // @synthesize baselineFileRelativePath=_baselineFileRelativePath;
@property(copy, nonatomic) NSURL *baselineFileURL; // @synthesize baselineFileURL=_baselineFileURL;
@property(copy) NSUUID *sessionIdentifier; // @synthesize sessionIdentifier=_sessionIdentifier;
@property(copy) XCTTestIdentifierSet *testsToSkip; // @synthesize testsToSkip=_testsToSkip;
@property(copy) XCTTestIdentifierSet *testsToRun; // @synthesize testsToRun=_testsToRun;
@property(copy, nonatomic) NSURL *testBundleURL; // @synthesize testBundleURL=_testBundleURL;
@property(copy) NSString *testBundleRelativePath; // @synthesize testBundleRelativePath=_testBundleRelativePath;
- (void)clearXcodeReportingConfiguration;
@property(readonly) XCTScreenCapturePolicy *effectiveScreenCapturePolicy;
@property(readonly) long long testMode;
@property(readonly, copy) NSString *testBundleName;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

#endif