#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTRepetitionPolicy : NSObject <NSSecureCoding>
{
    _Bool _repeatInNewRunnerProcess;
    _Bool _isDefault;
    long long _mode;
    long long _maximumIterations;
}

+ (_Bool)supportsSecureCoding;
+ (long long)modeFromString:(id)arg1;
+ (id)stringFromRepetitionMode:(long long)arg1;
+ (id)defaultRepetitionPolicy;
@property(readonly) _Bool isDefault; // @synthesize isDefault=_isDefault;
@property(readonly) _Bool repeatInNewRunnerProcess; // @synthesize repeatInNewRunnerProcess=_repeatInNewRunnerProcess;
@property(readonly) long long maximumIterations; // @synthesize maximumIterations=_maximumIterations;
@property(readonly) long long mode; // @synthesize mode=_mode;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)shouldRepeatWithTestFailure:(_Bool)arg1 iteration:(long long)arg2;
- (id)dictionaryRepresentation;
- (id)description;
- (id)initWithDictionary:(id)arg1;
- (id)initWithFixedIterations:(long long)arg1 repeatInNewRunnerProcess:(_Bool)arg2;
- (id)initRetryOnFailureWithMaximumIterations:(long long)arg1 repeatInNewRunnerProcess:(_Bool)arg2;
- (id)initUntilFailureWithMaximumIterations:(long long)arg1 repeatInNewRunnerProcess:(_Bool)arg2;
- (id)initWithRepetitionMode:(long long)arg1 maximumIterations:(long long)arg2 repeatInNewRunnerProcess:(_Bool)arg3;

@end

#endif