#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTScreenCapturePolicy : NSObject <NSSecureCoding>
{
    long long _captureFormat;
    long long _attachmentLifetime;
}

+ (_Bool)supportsSecureCoding;
+ (id)defaultPolicy;
@property(readonly, nonatomic) long long attachmentLifetime; // @synthesize attachmentLifetime=_attachmentLifetime;
@property(readonly, nonatomic) long long captureFormat; // @synthesize captureFormat=_captureFormat;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)dictionaryRepresentation;
- (id)description;
- (id)initWithDictionary:(id)arg1;
- (id)initWithCaptureFormat:(long long)arg1 attachmentLifetime:(long long)arg2;

@end

#endif