#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 170000 && __IPHONE_OS_VERSION_MAX_ALLOWED < 180000

#import "Xcode_15_0_XCTestCore_CDStructures.h"
#import "Xcode_15_0_SharedHeader.h"
#import <Foundation/Foundation.h>
#import <XCTest/XCTMeasureOptions.h>

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface XCTMeasureOptions ()
{
    _Bool _enableParallelizedSampling;
    _Bool _scheduleKickOffOnNewThread;
    _Bool _allowContinuousSampling;
    _Bool _discardFirstIteration;
    _Bool _traceCollectionEnabled;
    _Bool _memgraphCollectionEnabled;
    _Bool _perfdataAttachmentEnabled;
    unsigned long long _invocationOptions;
    unsigned long long _iterationCount;
    NSDictionary *_performanceTestConfiguration;
    NSArray *_performanceTraceConfigurations;
    NSString *_perfdataTestName;
    double _quiesceCpuIdlePercent;
    double _quiesceCpuIdleTimeLimit;
}

@property(nonatomic) double quiesceCpuIdleTimeLimit; // @synthesize quiesceCpuIdleTimeLimit=_quiesceCpuIdleTimeLimit;
@property(nonatomic) double quiesceCpuIdlePercent; // @synthesize quiesceCpuIdlePercent=_quiesceCpuIdlePercent;
@property(nonatomic) _Bool perfdataAttachmentEnabled; // @synthesize perfdataAttachmentEnabled=_perfdataAttachmentEnabled;
@property(nonatomic) _Bool memgraphCollectionEnabled; // @synthesize memgraphCollectionEnabled=_memgraphCollectionEnabled;
@property(nonatomic) _Bool traceCollectionEnabled; // @synthesize traceCollectionEnabled=_traceCollectionEnabled;
@property(nonatomic) _Bool discardFirstIteration; // @synthesize discardFirstIteration=_discardFirstIteration;
@property(retain, nonatomic) NSString *perfdataTestName; // @synthesize perfdataTestName=_perfdataTestName;
@property(copy, nonatomic) NSArray *performanceTraceConfigurations; // @synthesize performanceTraceConfigurations=_performanceTraceConfigurations;
@property(retain, nonatomic) NSDictionary *performanceTestConfiguration; // @synthesize performanceTestConfiguration=_performanceTestConfiguration;
@property(nonatomic) _Bool allowContinuousSampling; // @synthesize allowContinuousSampling=_allowContinuousSampling;
@property(readonly, nonatomic) unsigned long long instrumentAutomatic;
@property(nonatomic) _Bool allowConcurrentIterations;
- (void)applyPerformanceTestConfiguration;
@property(readonly, nonatomic) NSDictionary *instrumentOptions;
- (id)initWithInstrumentOptionsDictionary:(id)arg1;
- (id)init;

@end

#endif