#!/bin/bash

set -ueo pipefail

script_root=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "${script_root}/../.." && pwd)

source "$REPO_ROOT/Tests/Scripts/mock_generation.sh"

build_generator_if_needed
